### ISSUE TITLE
NullPointerException when accessing CPLC data of card

### ISSUE THREAD

**Issue by thotheolh** [martinpaljak/GlobalPlatformPro#100]
Below is the command issued in debug mode while accessing a SIM card

java -jar gp.jar -i -debug
GlobalPlatformPro unknown-development
Running on **********, Java 1.8.0_151 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] SCR301 0
SCardConnect("SCR301 0", T=*) -> T=0, 3B9F95801FC78031E073FE2113574A3305
2C323400BD
SCardBeginTransaction("SCR301 0")
Reader: SCR301 0
ATR: 3B9F95801FC78031E073FE2113574A33052C323400BD
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B9F95801FC78031E073FE2113574A330
52C323400BD

A>> T=0 (4+0000) 00A40400 00
A<< (0018+2) (47ms) 6F108408A000000003000000A5049F6501FF 9000
***** Card info:
A>> T=0 (4+0000) 80CA9F7F 00
A<< (0045+2) (0ms) 9F7F2A0005002CA2020181024022736925118198810005228713423027167
330271012FFFF167330271012FFFF 9000
Card CPLC:
ICFabricator: 0005
ICType: 002C
OperatingSystemID: A202
OperatingSystemReleaseDate: 0181
OperatingSystemReleaseLevel: 0240
ICFabricationDate: 2273
ICSerialNumber: 69251181
ICBatchIdentifier: 9881
ICModuleFabricator: 0005
ICModulePackagingDate: 2287
ICCManufacturer: 1342
ICEmbeddingDate: 3027
ICPrePersonalizer: 1673
ICPrePersonalizationEquipmentDate: 3027
ICPrePersonalizationEquipmentID: 1012FFFF
ICPersonalizer: 1673
ICPersonalizationDate: 3027
ICPersonalizationEquipmentID: 1012FFFF
***** CARD DATA
A>> T=0 (4+0000) 80CA0066 00
A<< (0051+2) (0ms) 6631732F06072A864886FC6B01600C060A2A864886FC6B020201016309060
72A864886FC6B03640B06092A864886FC6B040105 9000
Unknown tag: 31
***** KEY INFO
A>> T=0 (4+0000) 80CA00E0 00
A<< (0000+2) (0ms) 6985
SCardEndTransaction()
SCardDisconnect("SCR301 0", true)
Exception in thread "main" java.lang.NullPointerException
        at java.io.ByteArrayInputStream.<init>(Unknown Source)
        at org.bouncycastle.asn1.ASN1InputStream.<init>(Unknown Source)
        at pro.javacard.gp.GPData.get_key_template_list(GPData.java:158)
        at pro.javacard.gp.GlobalPlatform.getKeyInfoTemplate(GlobalPlatform.java
:369)
        at pro.javacard.gp.GPData.print_card_info(GPData.java:321)
        at pro.javacard.gp.GPTool.main(GPTool.java:433)

**Comment by martinpaljak** [comment]
You are not using the latest code. Either try the latest RC (or, in your case, update your tree)

**Comment by thotheolh** [comment]
Thanks. It works with a new version.
