### ISSUE TITLE
ACS ACOSJ 40K fix

### ISSUE THREAD

**Issue by TobiasKaiser** [martinpaljak/GlobalPlatformPro#101]
The GlobalPlatformPro tool needs some modification to lock my ACS ACOSJ 40K dual interface card (Java Card 3.0.4, Global Platform 2.2.1).

I was able to fix this problem for me by changing some key version in the source code from 1 to 0x20. See this commit from me: https://github.com/TobiasKaiser/GlobalPlatformPro/commit/16861b719c476eaffe66cb1209c111882415d772

This fix most likely breaks support for other cards. I have no idea how to fix this problem is a non-destructive manner.

I figured this out from a manual file from the card manufacturer:
"The Issuer Security Domain has three identical 16-byte initial static keys. The Key Version
Numbers of these keys is set to '20' and the Key Identifiers are set to '01', '02' and '03'
respectively. Unless otherwise requested by the Card Issuer, the value of any initial key is..." from https://www.acs.com.hk/download-manual/7881/USR-ACOSJ-Sample-Card-1.00.pdf

If it helps, Martin Paljak, I can send you one of the cards.

Best wishes

**Comment by martinpaljak** [comment]
The solution to your problem is on the next line of your change. That is, you should specify the key version on the command line.

The auto-detection of the key information from key template should make it more automagic, thus I leave the ticket open until I have had a look at it.

Feel free to send cards, always :) please e-mail me.

**Comment by TobiasKaiser** [comment]
If I remember correctly (I encountered the problem 2 months ago or so), I also tried the -new-keyver option before I changed the source code and somehow it did not work. Maybe this is because the `replace` variable is set to false then. But it could also be that I accidentally used the -key-ver option instead of the -new-keyver option. I will try again and update this issue in the next days then.

**Comment by martinpaljak** [comment]
Correct. Could you test with latest master?

**Comment by TobiasKaiser** [comment]
The latest master fixes this issue for me! After -lock, I can only access the card using the correct -key option. :+1: 

The only problem that I have now is that when I try to -unlock the card, it says "Template has bad length!" When I instead do a -lock with the default key, it works. Is this related to the previous problem? Here are the commands that I ran and the gp output: [test.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/1641014/test.txt)

Thanks!

**Comment by martinpaljak** [comment]
This should be fixed by 70e9b24. When locking the created SSD, you can simply use "gp -sdaid A0000001515351 -key 303BB82519C6D717D86F391C506F852F" which would create by default version 1 keys, or specify the new keyset version with "-new-keyver 4" (to create version 4 keys for the SSD)
