### ISSUE TITLE
Strict Warning-Card Cryptogram invalid

### ISSUE THREAD

**Issue by akritidogra** [martinpaljak/GlobalPlatformPro#105]
Hi,
I am new to java card. I am following http://blog.rchapman.org/posts/Smart_card_installing_Hello_World_on_a_Gemalto_IDPrime_PIV_2.0_card/ this blog to install simple applet. But it throws error. I think. I cant find right key. How to find key.
I'm getting these errors:
root@internet-OptiPlex-3040:/home/internet/Downloads# java -jar gp.jar gp -visa2 -key 47454D5850524553534F53414D504C45 -mode clr --list
pro.javacard.gp.GPException: STRICT WARNING: Card cryptogram invalid!
Card: 3B7273DE056B9782
Host: 2E25917C8C664A18
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
	at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:188)
	at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:498)
	at pro.javacard.gp.GPTool.main(GPTool.java:403)

**Comment by martinpaljak** [comment]
a) You really need to know the actual keying information for your card. Ask your vendor if unsure. b) please do follow the "support" section (namely, using -dvi switches)

**Comment by akritidogra** [comment]
I asked the vendor but he says I have to generate the keys. Can you please
let me know how to generate the keys?
