### ISSUE TITLE
key generation

### ISSUE THREAD

**Issue by akritidogra** [martinpaljak/GlobalPlatformPro#108]
I have a java card. I'm new to it. I tried performing commands and functions but I dont have its key. Vendor says I have to generate the key myself, he dont provide it. so please help me generate the key, the action how is it done?

**Comment by martinpaljak** [comment]
Sorry, this is not the way locks work. You need to have the key for the lock (or if you have a key, sometimes you need a lock for it - in this case a specific card).

If you need general assistance with JavaCard-s, paid consultation is possible.
