### ISSUE TITLE
Support for SCP03 mode 70 AES256 bit key diversification 

### ISSUE THREAD

**Issue by gmkbenjamin** [martinpaljak/GlobalPlatformPro#112]
This card that I have uses AES256 key and kdf in counter mode but I can't seem to get gp pro working with it.  
`
gp -r "Broadcom Corp Contacted SmartCard 0" -v -d -i 
GlobalPlatformPro v0.3.10rc7-7-g6ed0550-dirty
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Broadcom Corp Contacted SmartCard 0", T=*) -> T=1, 3BD6970081B1FE451F078031C1521118F9
SCardBeginTransaction("Broadcom Corp Contacted SmartCard 0")
Reader: Broadcom Corp Contacted SmartCard 0
ATR: 3BD6970081B1FE451F078031C1521118F9
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F078031C1521118F9

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (55ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0000) 80CA9F7F 00
A<< (0045+2) (31ms) 9F7F2A47906A1582314176009661330000114A1424114261331143613311446133130B00000000000000000000 9000
CPLC: ICFabricator=4790
      ICType=6A15
      OperatingSystemID=8231
      OperatingSystemReleaseDate=4176 (2014-06-25)
      OperatingSystemReleaseLevel=0096
      ICFabricationDate=6133 (2016-05-12)
      ICSerialNumber=0000114A
      ICBatchIdentifier=1424
      ICModuleFabricator=1142
      ICModulePackagingDate=6133 (2016-05-12)
      ICCManufacturer=1143
      ICEmbeddingDate=6133 (2016-05-12)
      ICPrePersonalizer=1144
      ICPrePersonalizationEquipmentDate=6133 (2016-05-12)
      ICPrePersonalizationEquipmentID=130B0000
      ICPersonalizer=0000
      ICPersonalizationDate=0000 (2010-01-01)
      ICPersonalizationEquipmentID=00000000

***** GET DATA:
A>> T=1 (4+0000) 80CA0042 00
A<< (0000+2) (47ms) 6A88
GET DATA(IIN): not supported: 0x6A88 (Referenced data not found)
A>> T=1 (4+0000) 80CA0045 00
A<< (0000+2) (47ms) 6A88
GET DATA(CIN): not supported: 0x6A88 (Referenced data not found)
A>> T=1 (4+0000) 80CA00C1 00
A<< (0005+2) (47ms) C10300000F 9000
GET DATA(SSC): 00000F
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00
A<< (0051+2) (46ms) 6631732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B040370 9000
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.2.1
-> GP Version: 2.2.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.3.112
-> GP SCP03 i=70
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00
A<< (0020+2) (47ms) E012C00401018820C00402018820C00403018820 9000
Version:   1 (0x01) ID:   1 (0x01) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   2 (0x02) type: AES  length:  32 (AES-256)
Version:   1 (0x01) ID:   3 (0x03) type: AES  length:  32 (AES-256)
SCardEndTransaction(Broadcom Corp Contacted SmartCard 0)
SCardDisconnect("Broadcom Corp Contacted SmartCard 0", true)

gp -r "Broadcom Corp Contacted SmartCard 0" -v -d -scp 3 -kdf3 -key 101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f
GlobalPlatformPro v0.3.10rc7-7-g6ed0550-dirty
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Broadcom Corp Contacted SmartCard 0", T=*) -> T=1, 3BD6970081B1FE451F078031C1521118F9
SCardBeginTransaction("Broadcom Corp Contacted SmartCard 0")
Reader: Broadcom Corp Contacted SmartCard 0
ATR: 3BD6970081B1FE451F078031C1521118F9
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F078031C1521118F9

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (47ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0008) 80500000 08 C7F066342583F2A6 00
A<< (0032+2) (201s697ms) 142461330000114A010001037011AD1A8DFBE5090FCAF003860BA2DC59000010 9000
[DEBUG] GlobalPlatform - Host challenge: C7F066342583F2A6
[DEBUG] GlobalPlatform - Card challenge: 11AD1A8DFBE5090F
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
[DEBUG] GlobalPlatform - SCP03 i=112
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F, DEK=type=RAW bytes=101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F, MAC=type=RAW bytes=101112131415161718191A1B1C1D1E1F202122232425262728292A2B2C2D2E2F}
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=51D392CF4944F796CDAEC0940FF7F924D71292CB4811A3D984CB49B9DD7E97A6 kcv=2908CD, DEK=type=AES bytes=DEACFE75FC27CCEC19806DDAED95DB151979759EE912FF2B959982E1CCFA3F6D kcv=1EB5D5, MAC=type=AES bytes=70522BF249CC3F09FA2E173B8D587DA631E681ADB5D876DA9F4F9FA61DB6D749 kcv=1E9E04}
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=0EE445BA1EA6B907D61BD86FC389F10906B42AA2B332D43331FF699F8F1C6346 kcv=9E6D61, DEK=type=AES bytes=DEACFE75FC27CCEC19806DDAED95DB151979759EE912FF2B959982E1CCFA3F6D kcv=1EB5D5, MAC=type=AES bytes=7869D86BE42339C2FCEF5151F536B903221099B24F37B2DE5005C7F110AECC75 kcv=08CFE2}
Read more from https://github.com/martinpaljak/GlobalPlatformPro/wiki/Keys
STRICT WARNING: Card cryptogram invalid!
Card: CAF003860BA2DC59
Host: 7E612E73636DB6C8
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
`

**Comment by gmkbenjamin** [comment]
Okay.... on-card key derived fine. Session key maybe? I will try to manually derive and compare.

**Comment by gmkbenjamin** [comment]
Session keys are fine as well.... Will try a virgin card tomorrow.

**Comment by martinpaljak** [comment]
I do not know a document describing a card key derivation scheme (from master key to enc-mac-dec keys), that could actually be "reliably and authoritatively" called "KDF mode". Thus do not take the per-card key derivation hiding at this moment behind `-kdf3`  as something that should reliably work _for you_. Do verify that it actually is the same method that is used by your system/vendor OR please provide a reference to some document that describes it or describes your derivation scheme.

Do have a look at https://github.com/martinpaljak/GlobalPlatformPro/wiki/Keys

I do not believe that there is an issue with deriving session keys for "SCP 03 i=70) (that is, from per-card dec-enc-mac do s-enc,s-mam, s-rmac), as GPPro by definition at this moment does NOT support offline scripts, the fact that there is pseudo-random card challenge should not matter at all.

Feel free to re-open this ticket if I misunderstand something or please do open a new one about the master->per-card derivation scheme if you have further references.

**Comment by martinpaljak** [comment]
Also, if you know from where to get the sample card with some known keys, let me know or ping me privately
