### ISSUE TITLE
Getting 6F02 on Oberthur COSMO 8.1 cards with -l option

### ISSUE THREAD

**Issue by gmkbenjamin** [martinpaljak/GlobalPlatformPro#113]
Getting 6F02 with -l option.

```
λ gp -r "Broadcom Corp Contacted SmartCard 0" -l -kdf3 -key 808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852 -v -d
GlobalPlatformPro v0.3.10rc7-7-g6ed0550-dirty
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
[ ] Broadcom Corp Contactless SmartCard 0
[ ] BROADCOM NFC Smartcard Reader 0
[*] Microsoft Virtual Smart Card 0
SCardConnect("Broadcom Corp Contacted SmartCard 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B
SCardBeginTransaction("Broadcom Corp Contacted SmartCard 0")
Reader: Broadcom Corp Contacted SmartCard 0
ATR: 3BD6970081B1FE451F878031C152211A4B
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B

A>> T=1 (4+0000) 00A40400 00
A<< (0066+2) (46ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B02020201630906072A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000
A>> T=1 (4+0008) 80500000 08 95C3C91BB179A3BF 00
A<< (0032+2) (78ms) 149480576000078C0100010370827BBF7447C06D7329DD896EBC4D6DF7000013 9000
[DEBUG] GlobalPlatform - Host challenge: 95C3C91BB179A3BF
[DEBUG] GlobalPlatform - Card challenge: 827BBF7447C06D73
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
[DEBUG] GlobalPlatform - SCP03 i=112
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, DEK=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, MAC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852}
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=D6CAABD673C7248CD7A9AC45914A9FC1B795C9D1954EF649E30F0D683F0368C6 kcv=48DA02, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=C9F96A6BA1ED6DE51E0680D3D25C1E05350DC1522B6737EEA886929581D4D2B0 kcv=BD7B5C}
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=ECD403D4D926658145A80A45650023FAE2B8D4A9C0F132ADF71DA6247616B7FB kcv=FF3777, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=5C417670E083A2EAE7BBE9D1F63AF1991F17BDDC2A1C527EF3310BC4104E3F03 kcv=FDC4D8}
[DEBUG] GlobalPlatform - Verified card cryptogram: 29DD896EBC4D6DF7
[DEBUG] GlobalPlatform - Calculated host cryptogram: 556B8DDD5068D75B
A>> T=1 (4+0016) 84820100 10 556B8DDD5068D75BF95ADDD614BEF24E
A<< (0000+2) (31ms) 9000
A>> T=1 (4+0010) 84F28002 0A 4F009F77F1E499234F17
A<< (0000+2) (148ms) 9000
A>> T=1 (4+0010) 84F24002 0A 4F0022B1058DD92B6D2D
A<< (0000+2) (454ms) 9000
A>> T=1 (4+0010) 84F22002 0A 4F00F10E417FD29F2269
A<< (0000+2) (344ms) 9000
A>> T=1 (4+0010) 84F21002 0A 4F0060A607E9B0D4FAD3
A<< (0000+2) (216ms) 6F02
[WARN] GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 0x6F02
SCardEndTransaction(Broadcom Corp Contacted SmartCard 0)
SCardDisconnect("Broadcom Corp Contacted SmartCard 0", true)
```

**Comment by martinpaljak** [comment]
6FXX usually refers to some internal exception. Can you please try with the latest version (to be pre-released to Github by Travis every minute now)

**Comment by gmkbenjamin** [comment]
Will do Martin. Not getting this on Oberthur COSMO v8.0 though. I was told the cards haven't changed that much. But it's not listing the contents though especially the applets.

**Comment by martinpaljak** [comment]
There was a stupid bug in the code as well, that "lost" the response from the card. So you really need to get the latest RC with at least 7f404e8d068c976e11be505a7d823985eedb29b1. 

It would be interesting to know if this makes the issue go away. 6f00 is "general exception" usually thus seeing 6f02 would be a pretty interesting issue.

**Comment by gmkbenjamin** [comment]
Getting the contents now but still getting 6F02

λ gp -r "Gemplus USB Smart Card Reader 0" -kdf3 -key 808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C53
7196577D508852 -v -d -l                                                                                
GlobalPlatformPro v0.3.10rc8-0-gf1dcf34                                                                
Running on Windows 10 10.0 amd64, Java 1.8.0_161 by Oracle Corporation                                 
# Detected readers from JNA2PCSC                                                                       
[*] Broadcom Corp Contacted SmartCard 0                                                                
[ ] Broadcom Corp Contactless SmartCard 0                                                              
[ ] BROADCOM NFC Smartcard Reader 0                                                                    
[*] Gemplus USB Smart Card Reader 0                                                                    
[*] Microsoft Virtual Smart Card 0                                                                     
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BD6970081B1FE451F878031C152211A4B        
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")                                               
Reader: Gemplus USB Smart Card Reader 0                                                                
ATR: 3BD6970081B1FE451F878031C152211A4B                                                                
More information about your card:                                                                      
    http://smartcard-atr.appspot.com/parse?ATR=3BD6970081B1FE451F878031C152211A4B                      
                                                                                                       
A>> T=1 (4+0000) 00A40400 00                                                                           
A<< (0066+2) (16ms) 6F408407A0000001510000A535732F06072A864886FC6B01600C060A2A864886FC6B020202016309060
72A864886FC6B03640B06092A864886FC6B0403709F6501FF 9000                                                 
[DEBUG] GlobalPlatform - Auto-detected ISD: A0000001510000                                             
A>> T=1 (4+0008) 80500000 08 726FA486419E8424 00                                                       
A<< (0032+2) (62ms) 149480576000078C01000103705CB17CF9D29E88CC780408C2550282F900001A 9000              
[DEBUG] GlobalPlatform - Host challenge: 726FA486419E8424                                              
[DEBUG] GlobalPlatform - Card challenge: 5CB17CF9D29E88CC                                              
[DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)                             
[DEBUG] GlobalPlatform - Will do SCP03 (3)                                                             
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C
537196577D508852, DEK=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852, 
MAC=type=RAW bytes=808CD8F1E4850B13DB50DCAA102C85DC6D877437C0D97A0C537196577D508852}                   
[DEBUG] PlaintextKeys - Derived per-card keys: {ENC=type=AES bytes=D6CAABD673C7248CD7A9AC45914A9FC1B795
C9D1954EF649E30F0D683F0368C6 kcv=48DA02, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE638
7BF2FCC389C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=C9F96A6BA1ED6DE51E0680D3D25C1E05350DC1522B6737EEA8
86929581D4D2B0 kcv=BD7B5C}                                                                             
[DEBUG] PlaintextKeys - Session keys: {ENC=type=AES bytes=2B126EEBE28E2EB5A4E65579DCA4049144E0DCB83D0E1
E4E0A10553790618384 kcv=D08528, DEK=type=AES bytes=A82C099ED6AF294DF1CA717E0A2CEE1A3415C4AE6387BF2FCC38
9C8B672FF643 kcv=EC37A1, MAC=type=AES bytes=27AE71EFB272C8E90B8BA2AF6042EB7471133F39E7798CD89B41C5151A0
BD0EA kcv=AE96CA, RMAC=type=AES bytes=EA28DC63A26D0C03A99733F4E48F2E11D5B297411DC784AF971122FDABBD01DD 
kcv=2A4336}                                                                                            
[DEBUG] GlobalPlatform - Verified card cryptogram: 780408C2550282F9                                    
[DEBUG] GlobalPlatform - Calculated host cryptogram: D0ED3E558DC6CE79                                  
A>> T=1 (4+0016) 84820100 10 D0ED3E558DC6CE794B6A13D201D73257                                          
A<< (0000+2) (16ms) 9000                                                                               
A>> T=1 (4+0010) 84F28002 0A 4F00EC462367BEC0368C 00                                                   
A<< (0020+2) (156ms) E3124F07A00000015100009F70010FC5039EFE80 9000                                     
A>> T=1 (4+0010) 84F24002 0A 4F004C57BFB3A4F1001A 00                                                   
A<< (0100+2) (449ms) E31B4F10A000000077010000061000FD000000269F70010FC503C18000E31B4F10A000000077010808
072000F1000005009F700107C503000000E3164F0BA0000003080000100001009F70010FC503100000E3104F05FFFFFFFFFF9F7
0010FC503000000 9000                                                                                   
A>> T=1 (4+0010) 84F22002 0A 4F00087186F940D21D32 00                                                   
A<< (0135+2) (351ms) E30D4F07A00000015153509F700101E3164F10A00000007701080807200000000000039F700101E316
4F10A00000007701080807200000000000029F700101E3164F10A00000007701080807200000000000019F700101E3164F10A00
000007701080807200000000000059F700101E3164F10A00000007701000006100000000000249F700101 9000             
A>> T=1 (4+0010) 84F21002 0A 4F00AD55CB924FE5DE72 00                                                   
A<< (0000+2) (218ms) 6F02                                                                              
[WARN] GlobalPlatform - GET STATUS failed for 80F21002024F0000 with 0x6F02                             
ISD: A0000001510000 (SECURED)                                                                          
     Privs:   SecurityDomain, CardLock, CardTerminate, CardReset, CVMManagement, TrustedPath, Authorize
dManagement, TokenVerification, GlobalDelete, GlobalLock, GlobalRegistry, FinalApplication, ReceiptGene
ration                                                                                                 
                                                                                                       
DOM: A000000077010000061000FD00000026 (PERSONALIZED) (|....w..........&|)                              
     Privs:   SecurityDomain, MandatedDAPVerification, TrustedPath                                     
                                                                                                       
APP: A000000077010808072000F100000500 (SELECTABLE) (|....w.... ......|)                                
     Privs:                                                                                            
                                                                                                       
APP: A000000308000010000100 (SELECTABLE (0xf)) (|...........|)                                         
     Privs:   CardLock                                                                                 
                                                                                                       
APP: FFFFFFFFFF (SELECTABLE (0xf)) (|.....|)                                                           
     Privs:                                                                                            
                                                                                                       
PKG: A0000001515350 (LOADED) (|....QSP|)                                                               
                                                                                                       
PKG: A0000000770108080720000000000003 (LOADED) (|....w.... ......|)                                    
                                                                                                       
PKG: A0000000770108080720000000000002 (LOADED) (|....w.... ......|)                                    
                                                                                                       
PKG: A0000000770108080720000000000001 (LOADED) (|....w.... ......|)                                    
                                                                                                       
PKG: A0000000770108080720000000000005 (LOADED) (|....w.... ......|)                                    
                                                                                                       
PKG: A0000000770100000610000000000024 (LOADED) (|....w..........$|)                                    
                                                                                                       
SCardEndTransaction(Gemplus USB Smart Card Reader 0)                                                   
SCardDisconnect("Gemplus USB Smart Card Reader 0", true)

**Comment by martinpaljak** [comment]
OK. I consider the WARN line a valid behaviour and this can be classified as a glitch/bug of the specific card. Do ask the vendor for possible reasons and file a new issue if there is something that could/should be changed in GPPro.
