### ISSUE TITLE
gp tool not working for scp03 supported cards

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#117]
My card is scp03 supported and when i am trying to run below command it gives me invalid cryptography error:

java -jar gp.jar -visa2 -key aes:47454D5850524553534F53414D504C45 -l 

Please advise.

**Comment by martinpaljak** [comment]
You need to know the keys and any diversification that is happening. If it fails, the information you have is probably wrong. If you are *absolutely* sure that you are doing everything right and there is a bug in GPPro, do file a technical bug.

More information: https://github.com/martinpaljak/GlobalPlatformPro/wiki/Keys

**Comment by naeemgik** [comment]
I am damn sure that the key is correct and it is working on same cards sample having scp02 support only. 

I just added "aes:"  due to below code snippet of GpPro:

public GPKey convert(String arg0) {
                  try {
                        String s = arg0.toLowerCase();
                        if (s.startsWith("aes:")) {
                              return new GPKey(HexUtils.hex2bin(s.substring("aes:".length())), Type.AES);
                        } else if (s.startsWith("3des:")) {
                              return new GPKey(HexUtils.hex2bin(s.substring("3des:".length())), Type.DES3);
                        } else {
                              // XXX: not rally nice to fall back to 3DES, but works for 90% of usecases.
                              return new GPKey(HexUtils.hex2bin(arg0), Type.DES3);
                        }
                  } catch (IllegalArgumentException e) {
                        throw new ValueConversionException(arg0 + " is not a valid key!");
                  }
            }

Why you are closing issue without proper solution?

**Comment by martinpaljak** [comment]
1. That snippet of code is from a very old version, please use the latest master/snapshot release.
2. If reporting an issue, please follow the guideline (that is, providing full debug log, as instructed in README)
3. 90% (if not 99%) of reports regarding authentication are because the keys are not correct.

**Comment by naeemgik** [comment]
Once code is modified and we run the below command it works on Gemalto Cards:

>gp  -v -debug --key 47454D5850524553534F53414D504C45 -div_aes_cmac -mode clr -s 00A4040000

[DEBUG] GlobalPlatform - Successfull Mutual Authentication.

So should you need to modify the source code?

**Comment by martinpaljak** [comment]
Apparently you have created your own key diversification method. Please refer to the documentation of that method or open a pull request with the fix/addition.
