### ISSUE TITLE
Notice for everyone looking for purchase cards from SmartcardFocus.com

### ISSUE THREAD

**Issue by 424778940z** [martinpaljak/GlobalPlatformPro#120]
First of all, allow me to apologize for "_abusing_" the Issues function to post this lol. 

Three days ago, I was looking for some programmable cards on SmartcardFocus, during checkout, I saw the shipping fee from US to Canada is more than the card costs, then I go and ask their sellers, here is what I got.

# TL;DR
>Summary it up, basically why the shipping is so expensive and they ask for bank transfer instead of credit card is because they want to prevent chargeback claims from credit card users (I mean people got the package but claim it was lost). Bank transfer will costs more than the shipping is not a good option either, therefore I decided just pay for the shipping and order them normally, and did a little complain about they put extra costs on customer for their own good. Then the magic happened, they just canceled my order lol, the email just literally like a mid-finger tell me to f@ck off.

>**If you planning to order cards from a company that ASSUME you are an asshole BY DEFAULT, think before you put the order.**

# Following are the emails

> ME:
Hello,
I live in Canada, and trying to buy a ACS card for development, it shows 14USD for shipping a single card... is it a cheaper way for shipping since it just one card not heavy or big at all...
Thanks,
Adam

> Matt:
I’m sorry, it’s the tracking that makes it cost so much. We could send it in a regular envelope for like $2 but we’d have no idea if it ever got there.  Which card are you interested in?
Kind Regards,
Matt
Phone +1 562 262 9642
Email   sales@smartcardfocus.us

> ME:
I'm interesting on this one 
https://www.smartcardfocus.us/shop/ilp/id~763/p/index.shtml

> Matt:
We do have that in stock. Sorry we can’t do anything to lower the delivery cost.
I guess if you wanted to pay by bank transfer we could do it.

> ME:
um, bank transfer will have some fees for that, is it possible use credit card?

>Matt:
 I’m sorry, that is not possible. Why don’t you just order more cards? The minimum shipping fee applies to something like 50 cards.

> ME:
I just need one or two for development, if the project works I may start use them for all my client employees. but I don't want invest too much when I'm not sure if it works.
I'm a local IT service provider, my client are some legal service company. I'm currently developing a system for them to control PCs and door access.
Is it possible to have a small discount ?

> Matt:
As a business owner with clients of your own I’m sure you can appreciate that credit card transactions require a signature on delivery to avoid chargeback claims for non-delivery and they incur a fee to process the transaction. As it stands, selling a single card is already a breakeven transaction for us. We take this risk as a business in the hopes that small projects like yours will take off and you’ll come back to buy thousands of cards.

> ME:
OK, may I know what carrier you are using to enforcing "signature on delivery" ?

> ME:
anyways, just use my credit card, and paid for the $14 shipping.
however, I really don't think put extra costs on customer just for prevent chargeback claims is a good idea

> Matt:
I just wanted to let you know that we are declining to fill your order. Your card has not been charged and we will not be accepting any future orders from you. Cheers

> ME:
what is wrong with me then?
is that how you do business?
ok. fine, I will order directly from Canada / China, you don't like to have business why not let others have, lol
sure, you may don't care such small orders, but I do believe no one gonna order 1000 card before they sure the project is working and ready for rolling out.
see you on Github, I will let all developers know you great attitude, good luck

>NO ANY REPLY

**Comment by martinpaljak** [comment]
Sorry, this is not a complaints forum, as you are - as you mentioned - abusing the issue tracking. But just for transparency, I will leave this here for 3 days and delete the issue on Monday. There are other vendors out there, you are free to choose your vendor, and for the record - I've had only good experiences with this specific one (albeit the UK branch). Please keep the issues tracking technical the next time.

**Comment by 424778940z** [comment]
> Sorry, this is not a complaints forum, you are - as you mentioned - abusing the issue tracking system. But just for transparency, I will leave this here for 3 days and delete the issue on Monday. There are other vendors out there (feel free to blog about your experience, post to news groups, comment on yelp or something else) and you are free to choose your vendor. For the record - I've had only good experiences with this specific one (albeit the UK branch).
> 
> Please post technical issues next time.
> 
> Also, as someone living in an EU country that many sellers (like Amazon et al) consider 3rd world, with no shipping available whatsoever - even at 3x the cost of the shipped item - I suggest you to appreciate your options and to whine less ;)

totally understand.

by the way you may want try taobao.com, it is the same company of aliexpress, they have more things than aliexpress, also sell to overseas with a cheaper shipping fee. However, it is in Chinese,  but I'm sure you can figure that out by google translate or just find a Chinese friend lol.
