### ISSUE TITLE
Unfused JCOP detected again

### ISSUE THREAD

**Issue by thotheolh** [martinpaljak/GlobalPlatformPro#121]
Below is the APDU executed over a J2E145 smart card by MoTechno ([https://www.motechno.com/buy/j2e145/](https://www.motechno.com/buy/j2e145/))

SCardConnect("Identiv SCR3500 A Contact Reader 0", T=*) -> T=1, 3BF91300008131FE
454A434F503234325233A2
SCardBeginTransaction("Identiv SCR3500 A Contact Reader 0")
A>> T=1 (4+0000) 00A40400 00
A<< (0000+2) (11ms) 6A82
A>> T=1 (4+0009) 00A40400 09 A000000167413000FF 00
A<< (0020+2) (21ms) 02B10140000000004E58323530420003F4477000 6A82
Unfused JCOP detected

**Comment by martinpaljak** [comment]
What do you want to change in GPPro? Ask the vendor or perform necessary pre-personalization steps yourself. GPPro shall not deal with proprietary card aspects, unless heavily justified and doable without NDA-s.

**Comment by thotheolh** [comment]
Is there a possibility of creating a JCOP fusing mode where the user only needs to supply the Transport Key, ISD Keys and card information ?

Maybe you can place this as a feature on the roadmap ?

**Comment by martinpaljak** [comment]
For JCOP-specific stuff, please refer to JCOP tools. Also, that part is covered by NDA-s, thus it would be possible only if you release full instructions/manuals as attachments to this ticket.
