### ISSUE TITLE
SCardTransmit got response 0x8010002f (SCARD_E_COMM_DATA_LOST: A communications error with the smart card has been detected.)

### ISSUE THREAD

**Issue by johnnytshi** [martinpaljak/GlobalPlatformPro#123]
**Describe the bug**
When I run "-l", I get the following error:
SCardTransmit got response 0x8010002f (SCARD_E_COMM_DATA_LOST: A communications error with the smart card has been detected.)

**Information about your card**
As much information as you have:
Not sure

**Expected behavior**
Expected to see the list of applets and packages, which used to work

**Full log**
GlobalPlatformPro v0.3.10rc7-0-g7208464
Running on Windows 10 10.0 amd64, Java 1.8.0_172 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Unknown Reader 0
[ ] JAVACOS Virtual Contact Reader 0
[ ] JAVACOS Virtual Contactless Reader 1
SCardConnect("Unknown Reader 0", T=*) -> T=0, 3B0D45534A434F53312E301924DCB6
SCardBeginTransaction("Unknown Reader 0")
Reader: Unknown Reader 0
ATR: 3B0D45534A434F53312E301924DCB6
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B0D45534A434F53312E301924DCB6

A>> T=0 (4+0000) 00A40400 00
A<< (0029+2) (94ms) 6F1B8408A000000003000000A50F730906072A864886FC6B019F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD: [AID: A000000003000000]
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
***** Card info:
A>> T=0 (4+0000) 80CA9F7F 00
A<< (0045+2) (86ms) 9F7F2A544600010001618000016180123456780001000161800001618000000000000000000000000000000000 9000
[CPLC ICFabricator=5446, ICType=0001, OperatingSystemID=0001, OperatingSystemReleaseDate=6180, OperatingSystemReleaseLevel=0001, ICFabricationDate=6180, ICSerialNumber=12345678, ICBatchIdentifier=0001, ICModuleFabricator=0001, ICModulePackagingDate=6180, ICCManufacturer=0001, ICEmbeddingDate=6180, ICPrePersonalizer=0000, ICPrePersonalizationEquipmentDate=0000, ICPrePersonalizationEquipmentID=00000000, ICPersonalizer=0000, ICPersonalizationDate=0000, ICPersonalizationEquipmentID=00000000]
A>> T=0 (4+0000) 80CA00E0 00
A<< (0020+2) (63ms) E012C00401FF8010C00402FF8010C00403FF8010 9000
Version: 255 (0xFF) ID: 1 (0x01) type: DES3 length: 16
Version: 255 (0xFF) ID: 2 (0x02) type: DES3 length: 16
Version: 255 (0xFF) ID: 3 (0x03) type: DES3 length: 16
Key version suggests factory keys
***** GET DATA:
A>> T=0 (4+0000) 80CA0042 00
A<< (0000+2) (35ms) 6A88
GET DATA(IIN) not supported0x6A88 (Referenced data not found)
A>> T=0 (4+0000) 80CA0045 00
A<< (0000+2) (38ms) 6A88
GET DATA(CIN) not supported: 0x6A88 (Referenced data not found)
A>> T=0 (4+0000) 80CA00C1 00
A<< (0004+2) (41ms) C1020015 9000
SSC 0015
*****
***** CARD DATA
A>> T=0 (4+0000) 80CA0066 00
A<< (0078+2) (129ms) 664C734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040215650B06092B8510864864020101660C060A2B060104012A026E0102 9000
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.21
-> GP SCP02 i=15
Tag 65: 1.3.656.840.100.2.1.1
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
***** KEY INFO
A>> T=0 (4+0000) 80CA00E0 00
A<< (0020+2) (62ms) E012C00401FF8010C00402FF8010C00403FF8010 9000
Version: 255 (0xFF) ID: 1 (0x01) type: DES3 length: 16
Version: 255 (0xFF) ID: 2 (0x02) type: DES3 length: 16
Version: 255 (0xFF) ID: 3 (0x03) type: DES3 length: 16
Key version suggests factory keys
A>> T=0 (4+0008) 80500000 08 A05E9C2EB6FFD4F2 00
<< SCARD_E_COMM_DATA_LOST
Failed to communicate with card in apdu4j.LoggingCardTerminal@56cbfb61: SCardTransmit got response 0x8010002f (SCARD_E_COMM_DATA_LOST: A communications error with the smart card has been detected.)
SCardEndTransaction(Unknown Reader 0)
SCardDisconnect("Unknown  Reader 0", true)

**Additional context**
I can still issue select adpu cmd

Any help is much apperciated

Johnny

**Comment by johnnytshi** [comment]
it appears that any cmd that starts with 80**** fails

**Comment by martinpaljak** [comment]
This is an issue with your (virtual?) reader or device (driver) behind it. GlobalPlatformPro requires a functioning "BIBO" (Bytes-In, Bytes-Out), in this case PC/SC. If this fails, there is not much we can do. CLA 0x80 is a valid CLA, so ...
