### ISSUE TITLE
Javacard buyers Guide and Tested Cards not updated for 3 years

### ISSUE THREAD

**Issue by makefu** [martinpaljak/GlobalPlatformPro#126]
**Describe the bug**
The javacard buyers guide and the "tested Cards" documentation hasn't been updated for almost 3 years. 

**Expected behavior**
Thes buyers guide and tested cards articles are essentially the `to-go` documents for getting a java card and it would be fantastic to have these documents updated to what is state-of-the-art. I think it would be also fine if the update says "essentially, nothing happened in the last 3 years".

**Full log**
google "javacard buy guide"

**Additional context**
Keep up your fantastic work!

**Comment by martinpaljak** [comment]
Absolutely! But it has to wait for a suitable timeslot ...

**Comment by martinpaljak** [comment]
buyers guide got a very slight update. Shops and tested cards section requires several resources (time/money/devices) and that happens when such resources are available.

Meanwhile, Petr's team has been doing a great work with JCAlgTest, that I should somehow link to from the buyers guide: https://www.fi.muni.cz/%7Exsvenda/jcalgtest/

**Comment by edent** [comment]
Is there a hardware guide for the equipment needed to write applets to a card? I'm assuming I can't use a standard Android device to run the JAR files. So what sort of USB (?) devices are supported by the software? Thanks.

**Comment by martinpaljak** [comment]
Going forward, all documentation (the mentioned guide included) shall live in the wiki.

Added some small updates when it comes to versions to use/expect in 2024, but the real sauce - list of shops with actually available cards - will need to be updated.

https://github.com/martinpaljak/GlobalPlatformPro/wiki/JavaCard-Buyer's-Guide
