### ISSUE TITLE
Release 0.3.10

### ISSUE THREAD

**Issue by Ekleog** [martinpaljak/GlobalPlatformPro#128]
Hello,

0.3.9 is ~2 years old. Would it make sense to release 0.3.10, or is there too much stuff still broken? :)

Anyway, thank you for working on GlobalPlatformPro!

**Comment by martinpaljak** [comment]
In fact, there will not be a 0.3.10, ever. The versioning was switched to date-based versions and a non-pre-release version should be published soon. Could be considered a RC, but without a pre-release flag in Github releases.

**Comment by Ekleog** [comment]
OK great, thanks! :)
