### ISSUE TITLE
`git describe` in build process makes GlobalPlatformPro harder to package than it could be

### ISSUE THREAD

**Issue by Ekleog** [martinpaljak/GlobalPlatformPro#129]
Hello,

I just want to mention that `git describe` being present in the build process is an issue when trying to build from tag-only non-full-source repositories. Which leads to me having to [patch the pom.xml](https://github.com/NixOS/nixpkgs/pull/44288/files#diff-3f80555b27d7cb249ab01d104b052e6eR21) to hardcode the output of `git describe` in order to package for NixOS.

If it was possible to somehow get rid of this requirement, I think it'd be great for packagers! :)

Anyway, thank you for GlobalPlatformPro!

**Comment by martinpaljak** [comment]
What do you mean? Can't you package a pre-build jar? I've found it to be invaluable information when people send logs that say "dirty" in the version.

**Comment by Ekleog** [comment]
Packaging pre-built packages is against my policy (that I may assume be the one of NixOS too, but there isn't (yet) an official position about that), so I avoid it as much as possible :)

Then, I have literally no knowledge of maven, so I don't really know what is possible to do with it or not. But I think, maybe the build system could try to `git describe` and if that fails, fallback to a hardcoded version that is set only for tagged releases?

**Comment by Ekleog** [comment]
The build is run from a tarball downloaded from GitHub, which doesn't include the `.git` repository.

**Comment by martinpaljak** [comment]
Why not from a Git checkout?

**Comment by Ekleog** [comment]
I unfortunately can't find again the source used, but a git checkout cannot easily be cached (at least in NixOS' setup, but intuitively in most setups too), unfortunately. So using them is the last-resort option.

Ideally, the `git describe` output could be overridden with an environment variable, this way if the environment variable is defined the `git describe` wouldn't run, and thus we would just have to set the environment correctly for the build to happen nicely, instead of patching the build system as currently done :)

**Comment by martinpaljak** [comment]
A patch along the lines what you described would be nice. Until that time I would say that building from a tag targzip (which could be a feature that can be turned off in Github) is not supported and a VC checkout is needed.

**Comment by Ekleog** [comment]
Just opened https://github.com/martinpaljak/GlobalPlatformPro/pull/130 which should more or less do this, even though unfortunately I won't be able to test it for a few days :/ should be easy to test, though :)

**Comment by martinpaljak** [comment]
#130 verified to work. Thanks!

**Comment by Ekleog** [comment]
Thank *you* for being that reactive! :)
