### ISSUE TITLE
Is it possible to run the tools via the TAMA driver?

### ISSUE THREAD

**Issue by vlsinitsyn** [martinpaljak/GlobalPlatformPro#132]
Hi, 
I have an NFC reader that works via the TAMA driver on Win. 
So, libnfc is working fine, for example. 
There is a java wrapper available that provides javax.smartcardio implementation: [https://sourceforge.net/projects/usbtama/](https://sourceforge.net/projects/usbtama/)
Is it possible to use the tools via the driver?

**Comment by martinpaljak** [comment]
Firs time I hear about TAMA.

Yes, but the --terminals option is really badly documented (might also be broken) Thanks for the notice!

Out of curiosity: where can one get such reader and can't you use a different (standard PC/SC) reader instead meanwhile?

**Comment by vlsinitsyn** [comment]
I've tried with --terminals, but it produces the error:
```
>gp --terminals usbtama-1.0.jar:nz.geek.rhubarb.usbtama.Provider -l
Exception in thread "main" java.security.NoSuchAlgorithmException: no such algorithm: PC/SC for provider USBTAMA
```
As far as I could understand, TAMA is a standard NXP protocol for their PN53x  readers:
[http://nfc-tools.org/index.php/Libnfc:pn53x-tamashell](http://nfc-tools.org/index.php/Libnfc:pn53x-tamashell)

On windows, such the devices are recognised as a USB device and their driver is based on the [libusb](https://sourceforge.net/p/libusb-win32/wiki/Home/) library.  
Then, [Libnfc](http://nfc-tools.org/index.php/Libnfc), a popular open source NFC library and all the software that uses the library is working with the device with no additional configuration required and independently from the Windows smart card service. 
The list of devices could be found on the Libnfc supported hardware page: [http://nfc-tools.org/index.php/Devices_compatibility_matrix](http://nfc-tools.org/index.php/Devices_compatibility_matrix)

**Comment by martinpaljak** [comment]
all transport issues have been removed from GPPro and for "advanced" transport or pc/sc thingies, GPPro should be executed via apdu4j. If you need assistance with thath, please ping me in private.
