### ISSUE TITLE
Smart cards can't be recognized from a USB type C port

### ISSUE THREAD

**Issue by paulchenlyft** [martinpaljak/GlobalPlatformPro#136]
**Information about your card**
As much information as you have:
1. Vendor: Gemalto card and smart card reader
2. Product: Gemalto USB Shell Token
3. Version: V2

My Macbook has only USB type C which requires an adapter to connect to a smart card reader of USB type A.

**Expected behavior**
I expect ATR and the reader to be found.

**Full log**
Re-run your command with `-d -v -i` switches
$ java -jar gp.jar -d -v -i
GlobalPlatformPro 18.09.14-0-gb439b52
Running on Mac OS X 10.13.6 x86_64, Java 11.0.1 by Oracle Corporation
# Detected readers from JNA2PCSC
No smart card readers with a card found

**Additional context**
I suspect it is due to the USB type adapter. Since in my old Mac with USB type A, the smart card can be found. Do I need to do anything special to read from USB type C?

Thanks

**Comment by startxc** [comment]
@paulchenlyft  Hi, how do you fixed this issue.
