### ISSUE TITLE
Returns 0 exit status when applet/package cannot be deleted

### ISSUE THREAD

**Issue by Zitrax** [martinpaljak/GlobalPlatformPro#142]
**Describe the bug**
Trying to delete an in use applet returns exit status 0.

**Expected behavior**
For scripting purposes I would expect the command to fail if the specified AID could not be deleted.  That deletion is not allowed is expected in this case, but I should not have to parse stdout/stderr to detect that.

**Full log**
I am assuming a full log is not needed. gp prints "`Could not delete AID: ANNNNNNNNNNNNNNNNNNN. Deletion not allowed. Some app still active.`" and `echo $?` returns 0.

**Additional context**
Same situation if trying to delete an AID that does not exist. gp prints `"Could not delete AID (not present on card): ANNNNNNNNNNNNNNNNNNN`" but returns exist status 0.

**Comment by martinpaljak** [comment]
Thanks, will fix. For the second case: it is !=0 if after the command the entity would be present. So if there is nothing to delete, all is good. That should remain like this, no ?

**Comment by Zitrax** [comment]
Maybe it should work like 'rm' on linux:

    rm foobar
    cannot remote 'foobar': No such file or directory
    echo $?
    1

    rm -f foobar
    echo $?
    0

Since there is a `--force` flag in gp too?

**Comment by martinpaljak** [comment]
Good idea, thanks!

**Comment by martinpaljak** [comment]
After giving it a look, it feels like I need to re-do a bunch of CLI logic that deals with working with multiple cards in one command. So this will take a bit more time to get done/right.

**Comment by martinpaljak** [comment]
Fixed by #232
