### ISSUE TITLE
Problem in changing card key

### ISSUE THREAD

**Issue by amheydari** [martinpaljak/GlobalPlatformPro#143]
I want to change the key of the card. But I can not change the card key.
Error 6A80 is given on the card.
I run the command as follows:
**java -jar gp_18.09.14.jar -lock 010B0371D78377B801F2D62AFC671D95 -d**
_GlobalPlatformPro 18.09.14-0-gb439b52
Running on Linux 4.9.0-kali3-amd64 amd64, Java 1.8.0_171 by Oracle Corporation
Detected readers from JNA2PCSC
[*] OMNIKEY CardMan (076B:5321) 5321 00 00
[ ] OMNIKEY CardMan (076B:5321) 5321 00 01
SCardConnect("OMNIKEY CardMan (076B:5321) 5321 00 00", T=*) -> T=0, 3B7F96000080318065B0850201F312FFFE829000
SCardBeginTransaction("OMNIKEY CardMan (076B:5321) 5321 00 00")
A>> T=0 (4+0000) 00A40400 00 
A<< (0103+2) (18ms) 6F658408A000000018434D00A559734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040105650B06092B8510864864020103660C060A2B060104012A026E01029F6E061291212101009F6501FF 9000
[TRACE] GPData -      [6F]
[TRACE] GPData -          [84] A000000018434D00
[TRACE] GPData -          [A5]
[TRACE] GPData -              [73]
[TRACE] GPData -                  [06] 2A864886FC6B01
[TRACE] GPData -                  [60]
[TRACE] GPData -                      [06] 2A864886FC6B02020101
[TRACE] GPData -                  [63]
[TRACE] GPData -                      [06] 2A864886FC6B03
[TRACE] GPData -                  [64]
[TRACE] GPData -                      [06] 2A864886FC6B040105
[TRACE] GPData -                  [65]
[TRACE] GPData -                      [06] 2B8510864864020103
[TRACE] GPData -                  [66]
[TRACE] GPData -                      [06] 2B060104012A026E0102
[TRACE] GPData -              [9F6E] 129121210100
[TRACE] GPData -              [9F65] FF
[DEBUG] GlobalPlatform - Auto-detected ISD: A000000018434D00
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
[TRACE] GlobalPlatform - Generated host challenge: 5820B0D2E5E596A8
A>> T=0 (4+0008) 80500000 08 5820B0D2E5E596A8 00
A<< (0028+2) (96ms) 4D004A0008C7238A2D730101E4675B793B59E1B90A5D4E0922380891 9000
[DEBUG] GlobalPlatform - Host challenge: 5820B0D2E5E596A8
[DEBUG] GlobalPlatform - Card challenge: E4675B793B59E1B9
[DEBUG] GlobalPlatform - Card reports SCP01 with key version 1 (0x01)
[DEBUG] GlobalPlatform - Will do SCP01 (1)
[DEBUG] PlaintextKeys - Card keys: {ENC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, MAC=type=RAW bytes=404142434445464748494A4B4C4D4E4F, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[TRACE] PlaintextKeys - Session keys: {ENC=type=DES3 bytes=15E27C1CD59A9670AB94DA801F11C5CF kcv=56112D, MAC=type=DES3 bytes=15E27C1CD59A9670AB94DA801F11C5CF kcv=56112D, DEK=type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[DEBUG] GlobalPlatform - Verified card cryptogram: 0A5D4E0922380891
[DEBUG] GlobalPlatform - Calculated host cryptogram: 8B21C78AFA59BF8E
A>> T=0 (4+0016) 84820100 10 8B21C78AFA59BF8E58A89DCF0C2A7DCB
A<< (0000+2) (46ms) 9000
[TRACE] GPData - GET DATA(Key Info Template)
A>> T=0 (4+0008) 84CA00E0 08 AEF3DC4D6FCDF934 00
A<< (0038+2) (20ms) E024C00401018110C00402018010C00403018010C00401028110C00402028110C00403028110 9000
[TRACE] GPData -      [E0]
[TRACE] GPData -          [C0] 01018110
[TRACE] GPData -          [C0] 02018010
[TRACE] GPData -          [C0] 03018010
[TRACE] GPData -          [C0] 01028110
[TRACE] GPData -          [C0] 02028110
[TRACE] GPData -          [C0] 03028110
[DEBUG] GlobalPlatform - PUT KEY version 1
[TRACE] GlobalPlatform - PUT KEY:type=DES3 version=1 (0x01) id=1 (0x01) bytes=010B0371D78377B801F2D62AFC671D95 kcv=F2DCDD
[TRACE] GlobalPlatform - PUT KEY:type=DES3 version=1 (0x01) id=2 (0x02) bytes=010B0371D78377B801F2D62AFC671D95 kcv=F2DCDD
[TRACE] GlobalPlatform - PUT KEY:type=DES3 version=1 (0x01) id=3 (0x03) bytes=010B0371D78377B801F2D62AFC671D95 kcv=F2DCDD
[TRACE] GPData - GET DATA(Key Info Template)
A>> T=0 (4+0008) 84CA00E0 08 D14FF607D9E1916A 00
A<< (0038+2) (21ms) E024C00401018110C00402018010C00403018010C00401028110C00402028110C00403028110 9000
[TRACE] GPData -      [E0]
[TRACE] GPData -          [C0] 01018110
[TRACE] GPData -          [C0] 02018010
[TRACE] GPData -          [C0] 03018010
[TRACE] GPData -          [C0] 01028110
[TRACE] GPData -          [C0] 02028110
[TRACE] GPData -          [C0] 03028110
A>> T=0 (4+0075) 84D80181 4B 01801001F2D62AFC671D9575C4C08ED4FCC69303F2DCDD801001F2D62AFC671D9575C4C08ED4FCC69303F2DCDD801001F2D62AFC671D9575C4C08ED4FCC69303F2DCDD4584E9E4F81281A7
A<< (0000+2) (72ms) 6A80
PUT KEY failed: 0x6A80 (Wrong data/incorrect values in data)_

The card is made by Gemalto.Card Specifications:
**java -jar gp_18.09.14.jar -i**
GlobalPlatformPro 18.09.14-0-gb439b52
Running on Linux 4.9.0-kali3-amd64 amd64, Java 1.8.0_171 by Oracle Corporation
Reader: OMNIKEY CardMan (076B:5321) 5321 00 00
ATR: 3B7F96000080318065B0850201F312FFFE829000
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B7F96000080318065B0850201F312FFFE829000

[WARN] GPData - Invalid CPLC date: 4A00
CPLC: ICFabricator=4090
      ICType=7870
      OperatingSystemID=1291
      OperatingSystemReleaseDate=2121 (2012-04-30)
      OperatingSystemReleaseLevel=0100
      ICFabricationDate=4A00 (invalid date format)
      ICSerialNumber=08C7238A
      ICBatchIdentifier=2D73
      ICModuleFabricator=1002
      ICModulePackagingDate=5067 (2015-03-08)
      ICCManufacturer=4193
      ICEmbeddingDate=5067 (2015-03-08)
      ICPrePersonalizer=4194
      ICPrePersonalizationEquipmentDate=5067 (2015-03-08)
      ICPrePersonalizationEquipmentID=00000007
      ICPersonalizer=0000
      ICPersonalizationDate=0000 (2010-01-01)
      ICPersonalizationEquipmentID=00000000

IIN: 42050001020304
CIN: 450805060708090A0B0C
Card Data: 
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.1.5
-> GP SCP01 i=05
Tag 65: 1.3.656.840.100.2.1.3
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
-> JavaCard v2
Card Capabilities: 
Version:   1 (0x01) ID:   1 (0x01) type: DES3 length:  16 
Version:   1 (0x01) ID:   2 (0x02) type: DES3 length:  16 
Version:   1 (0x01) ID:   3 (0x03) type: DES3 length:  16 
Version:   2 (0x02) ID:   1 (0x01) type: DES3 length:  16 
Version:   2 (0x02) ID:   2 (0x02) type: DES3 length:  16 
Version:   2 (0x02) ID:   3 (0x03) type: DES3 length:  16

**Comment by martinpaljak** [comment]
Still experiencing this with latest master?

**Comment by martinpaljak** [comment]
Even if still an issue with master that was not fixed by #215 the issue would be totally different now. Closing as stale.
