### ISSUE TITLE
Typos in error messages

### ISSUE THREAD

**Issue by LeonardOneWave** [martinpaljak/GlobalPlatformPro#144]
I found some (very small) typos into log and exception messages:
   - "SCP 01" instead of "SCP" 02 in IllegalArgumentException of deriveSessionKeySCP02 method of PlaintextKeys class
   - "No ruleS found" instead of "No rule found" in printList method of SEAccessControl class

A patch to correct those is attached.
[typos.patch.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/2723865/typos.patch.txt)

**Comment by Nucnay3428** [comment]
Ok
