### ISSUE TITLE
Expose apdu4j parameter to set APDU communication protocol

### ISSUE THREAD

**Issue by zhangtaii** [martinpaljak/GlobalPlatformPro#146]
Expose the [apdu4j](https://github.com/martinpaljak/apdu4j/blob/master/README.md) parameter `-t`,

Reference:
---
 * The same with forced T=0 protocol (similar for T=1):

       sc -t0 -a 00A40C0000

**Comment by martinpaljak** [comment]
What's the rationale?

**Comment by zhangtaii** [comment]
The default protocol `apdu4j` used for `connect` is `*`.
For my card which is `T=0`, after the `connect`, the reader use `T=1` for communication, that is wrong, so force it to use `T=0` is needed.

Logs:
```bash
GlobalPlatformPro 18.09.14-0-gb439b52
Running on Mac OS X 10.14 x86_64, Java 1.8.0_192 by Oracle Corporation
# Detected readers from JNA2PCSC
[ ] ACS ACR1281 1S Dual Reader(1)
[*] ACS ACR1281 1S Dual Reader(2)
[ ] ACS ACR1281 1S Dual Reader(3)
SCardConnect("ACS ACR1281 1S Dual Reader(2)", T=*) -> T=1, 3B8F80018031C052184C6402006471838390009A
SCardBeginTransaction("ACS ACR1281 1S Dual Reader(2)")
Reader: ACS ACR1281 1S Dual Reader(2)
```

**Comment by martinpaljak** [comment]
But the card does support T=1. What is the issue you are facing with T=1? Could you provide the log with "-d -v -i" added to the failing command?

**Comment by martinpaljak** [comment]
This has nothing to do with t0/t1, you need to send the APDU-s to the right applet (meaning a SELECT before APDU-s)

**Comment by zhangtaii** [comment]
Thanks for your help, I solved the problem by sending the SELECT and subsequent APDUs in a single command. 

```
gpj -dv -a SELECT_APDU -a FIRST_COMMAND_APDU -a SECOND_COMMAND_APDU -a THIRD_COMMAND_APDU
```

The lesson I got here is that if you send APDUs one by one with this tool, the context is not persisted, so the first SELECT status is lost for the subsequent command.
