### ISSUE TITLE
README.md may be out of date

### ISSUE THREAD

**Issue by kategray** [martinpaljak/GlobalPlatformPro#156]
Looking through README.md, it looks like the options may use an older format.  Using gp.exe, the option to install (for example) is --install, not -install.

To install an applet as default, I use `gp.exe --install [filename.cap] --default`.

README.md also refers to the -sdomain option, which appears to no longer exist.

**Comment by martinpaljak** [comment]
As the CLI has got a major overhaul (still WIP) the README shall also be re-done. Eventually it will be shrinked to a way smaller version and wiki used instead for live docs.

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/GlobalPlatformPro/wiki is getting up to date docs. README will be shrinked to minimal in next release.

**Comment by martinpaljak** [comment]
Better late than never, README has been shrunk
