### ISSUE TITLE
gp --install results in IllegalArgumentException

### ISSUE THREAD

**Issue by fridgecow** [martinpaljak/GlobalPlatformPro#157]
**Describe the bug**
Attempting to install JCardTest (and other test CAPs) on the ACOSJ 40K using ACR122U on linux (kernel 4.19) results in IllegalArgumentException. Logs (and cap) attached.

```
Exception in thread "main" java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Buffer.java:244)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmitImpl(Smartcardio.java:806)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmit(Smartcardio.java:688)
        at apdu4j.LoggingCardTerminal$LoggingCard$LoggingCardChannel.transmit(LoggingCardTerminal.java:248)
        at pro.javacard.gp.GlobalPlatform.transmit(GlobalPlatform.java:520)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:625)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:545)
        at pro.javacard.gp.GPTool.main(GPTool.java:500)
```

**Information about your card**
The card is an ACOSJ 40K bought from https://www.smartcardfocus.com/shop/ilp/id~790/acosj-dual-interface-java-card-40k/p/index.shtml

The reader is a cheap ACR122U-A9

**Expected behavior**
Installation succeeds.

**Full log**
[debug.zip](https://github.com/martinpaljak/GlobalPlatformPro/files/2974014/debug.zip)

**Additional context**
Previously installed successfully on different cards of this same model of card and reader.

I also believe that this has bricked one or two cards I've tried before, too.

**Comment by martinpaljak** [comment]
This is a known crappy reader. Can you try some other readers?

**Comment by fridgecow** [comment]
I thought that might be the case - I'll source another reader and report back.

**Comment by martinpaljak** [comment]
Try Feitian 502 or the 1252 "nfc iii" reader from acs

**Comment by martinpaljak** [comment]
This looks like an empty or otherwise weird response from reader/pcscd. Are you using the acsccid or original libccid driver?

**Comment by fridgecow** [comment]
I believe I'm using the default for Ubuntu 18.04, and pcscd - how would I check?

**Comment by martinpaljak** [comment]
You can try installing and removing this package: https://packages.ubuntu.com/search?keywords=libacsccid

(the reader name should probably change if using this driver vs libccid)

I recommend the official CCID driver and readers that work with it, but this is from ACS.

**Comment by fridgecow** [comment]
Looks like I was using libccid. Installing libacsccid does update the reader name, but does not help with the IllegalArgumentException, so I'll try a different reader.

**Comment by martinpaljak** [comment]
Alternatively, could you try with latest _stable_ release `-bs 240` option?

**Comment by martinpaljak** [comment]
Closing as stale
