### ISSUE TITLE
SCP03 RAPDU decryption fails if no data is returned

### ISSUE THREAD

**Issue by tsenger** [martinpaljak/GlobalPlatformPro#158]
**Describe the bug**
I use a applet on a G+D JavaCard which uses Globalplatforms SecureChannel. The applet uses SCP03 mode 0x33 (enc and mac for CAPDU and RAPDUs). If mode is enc, mac, renc and rmac selected and the card doesn't return (encrypted) data (tag 80) then GlobalPlatformPro throws Exception:
`Failed to communicate with card in apdu4j.LoggingCardTerminal@4b952a2d: Secure channel failure: APDU unwrapping failed`
Full command I used:
`java -jar gp.jar --key-enc xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --key-mac xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --key-dek xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --mode enc --mode mac --mode renc --mode rmac --sdaid D276000005123455 -s 80c4000008010203040506070800 -d`

**Information about your card**
G+D Sm@rtCafe Expert 7.0

**Expected behavior**
GlobalPlatformPro should recognize if there is no encrypted data included in the ResponseAPDU and skip the encryption of no data.

**Full log**

> GlobalPlatformPro 19.01.22-0-gf94d7f5
> Running on Linux 4.15.0-46-generic amd64, Java 1.8.0_201 by Oracle Corporation
> # Detected readers from JNA2PCSC
> [*] REINER SCT cyberJack RFID basis 00 00
> SCardConnect("REINER SCT cyberJack RFID basis 00 00", T=*) -> T=1, 3B8980015343453720000020204A
> SCardBeginTransaction("REINER SCT cyberJack RFID basis 00 00")
> Reader: REINER SCT cyberJack RFID basis 00 00
> ATR: 3B8980015343453720000020204A
> More information about your card:
>     http://smartcard-atr.appspot.com/parse?ATR=3B8980015343453720000020204A
> 
> A>> T=1 (4+0008) 00A40400 08 D276000005123455 00
> A<< (0015+2) (89ms) 4544456E634170706C65745F302E33 9000
> A>> T=1 (4+0000) 80CA9F7F 00 
> A<< (0000+2) (7ms) 6985
> A>> T=1 (4+0000) 00CA9F7F 00 
> A<< (0000+2) (7ms) 6985
> A>> T=1 (4+0000) 80CA0042 00 
> A<< (0000+2) (6ms) 6985
> A>> T=1 (4+0000) 80CA0045 00 
> A<< (0000+2) (8ms) 6985
> Card Data: 
> A>> T=1 (4+0000) 80CA0066 00 
> A<< (0000+2) (7ms) 6985
> Card Capabilities: 
> A>> T=1 (4+0000) 80CA0067 00 
> A<< (0000+2) (7ms) 6985
> A>> T=1 (4+0000) 80CA00E0 00 
> A<< (0000+2) (6ms) 6985
> A>> T=1 (4+0008) 80500000 08 FCF0FB6EAB11BF57 00
> A<< (0032+2) (54ms) 00000604002C000A990E0103700C4CE7320F311AC511ED7023909E4103000096 9000
> A>> T=1 (4+0016) 84823300 10 351EE508B3ED17C0AD9441AEC887A263
> A<< (0000+2) (20ms) 9000
> A>> T=1 (4+0024) 84C40000 18 3D21A08BAF8E3B26307587D8E232FDCE983F895FA80550AF 00
> A<< (0008+2) (40ms) 371B98E06BB6DAFA 9000
> Failed to communicate with card in apdu4j.LoggingCardTerminal@29ca901e: Secure channel failure: APDU unwrapping failed
> SCardEndTransaction(REINER SCT cyberJack RFID basis 00 00)
> SCardDisconnect("REINER SCT cyberJack RFID basis 00 00", true)
> 
> [DEBUG] GlobalPlatform - (I)SD AID: D276000005123455
> [WARN] GlobalPlatform - Could not parse SELECT response: null
> [TRACE] GPData - GET DATA(CPLC)
> [WARN] GPData - GET DATA(CPLC) not supported
> [TRACE] GPData - GET DATA(IIN)
> [WARN] GPData - GET DATA(IIN) not supported
> [TRACE] GPData - GET DATA(CIN)
> [WARN] GPData - GET DATA(CIN) not supported
> [TRACE] GPData - GET DATA(Card Data)
> [WARN] GPData - GET DATA(Card Data) not supported
> [TRACE] GPData - GET DATA(Card Capabilities)
> [WARN] GPData - GET DATA(Card Capabilities) not supported
> [TRACE] GPData - GET DATA(Key Info Template)
> [WARN] GPData - GET DATA(Key Info Template) not supported
> [TRACE] GlobalPlatform - Generated host challenge: FCF0FB6EAB11BF57
> [DEBUG] GlobalPlatform - Host challenge: FCF0FB6EAB11BF57
> [DEBUG] GlobalPlatform - Card challenge: 0C4CE7320F311AC5
> [DEBUG] GlobalPlatform - Card reports SCP03 i=70 with key version 1 (0x01)
> [DEBUG] GlobalPlatform - Will do SCP03 (3)
> [DEBUG] PlaintextKeys - Card keys: {DEK=type=RAW bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, ENC=type=RAW bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, MAC=type=RAW bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
> [TRACE] PlaintextKeys - Session keys: {DEK=type=RAW bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, ENC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=0F6352, MAC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=72B7EF, RMAC=type=AES bytes=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx kcv=1E9764}
> [DEBUG] GlobalPlatform - Verified card cryptogram: 11ED7023909E4103
> [DEBUG] GlobalPlatform - Calculated host cryptogram: 351EE508B3ED17C0
> 

**Additional context**
I think I localized the problem in class "SCP03Wrapper" in line 156 
` if (renc) {`
I change for testing to 
`if (renc && response.getData().length>0) {`
which worked fine for me.

**Comment by martinpaljak** [comment]
I hope fixed by #159  ?

**Comment by tsenger** [comment]
Yes, it is. Thanks!
