### ISSUE TITLE
Error when uninstalling an applet

### ISSUE THREAD

**Issue by rb-anssi** [martinpaljak/GlobalPlatformPro#165]
### Describe the bug
It seems that a regression might have been introduced with commit c8dad37315266b2d5b81dadcece87145c0b583cb. The '--uninstall' option for gp.jar provides a '0x6A80' error when trying to remove an existing applet.

Bisecting to the previous commit 5fd24244c810d6f4aaf964c5b9702efcd6ac4c7c allows to get back a working '--uninstall' option on the same card and with the same applet.

The error log (full trace provided below):

```
$ java -jar ./externals/globalplatformpro/target/gp.jar --uninstall ex.cap -v 
GlobalPlatformPro 19.01.22-5-gc8dad37
Running on Linux, Java 1.8.0_212 by Oracle Corporation
Reader: OMNIKEY AG CardMan 3121 00 00
ATR: 3BF91300008031FE454A434F503234325232A2
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BF91300008031FE454A434F503234325232A2

[DEBUG] GlobalPlatform - Auto-detected ISD: A000000151000000
...
[DEBUG] DMTokenGenerator - Adding tag 0x9E before Delete Token
[DEBUG] DMTokenGenerator - No private key for token generation provided
Deletion failed: 0x6A80 (Wrong data/incorrect values in data)
```

### Information about your card
As much information as you have:
1. Vendor = NXP
2. Product = JCOP (J3D081)
3. Version = J3D081

### Expected behavior

The applet should be properly deleted with '--uninstall'.

### Full log

[gp_log.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/3163650/gp_log.txt)

Thanks in advance for your valuable help,

**Comment by martinpaljak** [comment]
Thanks for noticing.
That PR was merged with the clause that it will be re-written a bit, to support static tokens. Will be fixed with that change.

**Comment by rb-anssi** [comment]
@martinpaljak,

Thank  you very much for the follow-up and the confirmation!
Waiting for the fix to be merged in master then!

Regards,

**Comment by martinpaljak** [comment]
This should be fixed in latest release
