### ISSUE TITLE
can't use param other than 'C9'

### ISSUE THREAD

**Issue by cocobear** [martinpaljak/GlobalPlatformPro#17]
the definition of installAndMakeSelectable is 
```
 public void installAndMakeSelectable(AID packageAID, AID appletAID, AID instanceAID, byte privileges, byte[] installParams,
			byte[] installToken)
```
installParams just use 'C9' tag, but accroding to the GP specification 'C9' tag is only one of the install params, there is 'EF' ,'EA', 'B6' params tags, so  perhaps  *'-params'* should just pass throught all data not suppose the data is kind of 'C9' tag.  just like *gpj* did,  so I can use param like this:
```
gp -v -d -install test.cap -params C900EA1B80
0DFF0012010100000003C0000100810400010000820400010000
```

**Comment by martinpaljak** [comment]
Okay, I'll change the command line tool to only append c9 if the paramters don't start with c9

**Comment by cocobear** [comment]
I just have a pull request, please have a look at it, I think that is more sensitive solution.

**Comment by martinpaljak** [comment]
Did this work for you ?

**Comment by cocobear** [comment]
Yes, it worked.
