### ISSUE TITLE
Card Applet Response

### ISSUE THREAD

**Issue by hermannkouadio** [martinpaljak/GlobalPlatformPro#179]
Hi, 
I'm new in javacard applet development and I don't understand something about applet response: like this: Recv: 99 90.
I'm using ExtendedLength for my applet.
But, when I test my Applet from PyApduTool, response's different.

![responseAPDU](https://user-images.githubusercontent.com/12629070/60590312-32372300-9d8b-11e9-94b1-07e9e5b634c9.png)
Can someone help me to retrieve data from real card ?

**Comment by martinpaljak** [comment]
Is there an issue with GPPro?

**Comment by hermannkouadio** [comment]
No.
But if you can help me, it'll be great.

Thanks
