### ISSUE TITLE
Gemalto ID Core 3140 SCP03 defaulting to SCP02 w Plaintext Keys

### ISSUE THREAD

**Issue by maatcha01** [martinpaljak/GlobalPlatformPro#182]
I'm working with a Gemalto IDCORE 3140 card which only supports SCP03.  Gemalto uses a custom diversification algorithm with these cards and I have calculated the static keys using the mother key value.  When specifying the keys global platform returns a warning [WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02 and then the command fails with 0X57.

Am I missing something with my command?

C:\Tools\Global Platform Pro>gp -v -d --key-dek XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --key-enc XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX --key-mac XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -l
GlobalPlatformPro 19.06.16-0-gbaccf34
Running on Windows 10 10.0 amd64, Java 1.8.0_221 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Gemplus USB Smart Card Reader 0
[ ] JAVACOS Virtual Contact Reader 0
[ ] JAVACOS Virtual Contactless Reader 1
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=0, 3B7F96000080318065B0855956FB12FFFE829000
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3B7F96000080318065B0855956FB12FFFE829000
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B7F96000080318065B0855956FB12FFFE829000

A>> T=0 (4+0000) 00A40400 00
A<< (0104+2) (20ms) 6F668408A000000018434D00A55A734B06072A864886FC6B01600B06092A864886FC6B020203630906072A864886FC6B03640B06092A864886FC6B040310650D060B2A864886FC6B0507020000660C060A2B060104012A026E01039F6E061291709004009F6501FF 9000
[DEBUG] GPSession - Auto-detected ISD: A000000018434D00
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[WARN] PlaintextKeys - Don't know how to calculate KCV, defaulting to SCP02
[INFO] GPSession - Using card master keys: ENC=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (KCV: ADC2E7) MAC=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (KCV: 1B660E) DEK=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (KCV: 920D7E) for null
[TRACE] GPSession - Generated host challenge: 3918CC5C9540D2AB
A>> T=0 (4+0008) 80500000 08 3918CC5C9540D2AB 00
<< (6ms) SCardTransmit got response 0x57 (null: null)
Failed to communicate with card in apdu4j.terminals.LoggingCardTerminal@5702b3b1: Transmit failed: SCardTransmit got response 0x57 (null: null)
SCardEndTransaction("Gemplus USB Smart Card Reader 0")
SCardDisconnect("Gemplus USB Smart Card Reader 0", true) tx:5/rx:106

**Comment by martinpaljak** [comment]
It is a warning for kcv calculation. Feel free to ignore. I would try a different reader or non-windows environment.

**Comment by maatcha01** [comment]
Thanks for the response Martin - Should the tool be defaulting to SCP02 in that case?  I think that's where the issue is given this card supports SCP03 only with AES keys.   Actually looking at the manual I think the KCV is non standard as well.  01..01h (16 bytes)  instead of 00.00h (8 bytes)

**Comment by martinpaljak** [comment]
Check #160 for hints on the 0x57 issue. I suggest removing Gemalto driver and using the Windows CCID driver. The somewhat confusing warning regarding KCV shall be dealt with somehow as a separate issue.

**Comment by martinpaljak** [comment]
#220 removed the confusing warning regarding KCV-s
