### ISSUE TITLE
Gemalto CT30 Card reader issue

### ISSUE THREAD

**Issue by saziz0926** [martinpaljak/GlobalPlatformPro#183]
This is a great tool.  I am running it in Windows 10 Home Edition.

I am using Gemalto MD 830 B smartcard and CT30 USB smartcard reader.

When I run the command gp --initialize-card, I get the following error.  Any help is appreciated. I have hit a wall now.

D:\Downloads\SatochipApplet-master\SatochipApplet-master>gp --initialize-card
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
Failed to communicate with card in JnaCardTerminal{scardHandle=SCardContext{cd00000100000001}, name=Gemalto USB Smart Card Reader 0}: SCardTransmit got response 0x57 (null: null)

Kind regards,

**Comment by martinpaljak** [comment]
Can you please provide a full debug log as instructed in README?

The issue is the same as #160 and #182 and probably has something to do with a possible fix in jnasmartcardio. Meanwhile I'd recommend either using non-Windows operating system, Windows default CCID driver or another reader.

**Comment by saziz0926** [comment]
Thanks Martinpaljak/Globalplatformpro very much.

Kind regards
Shah

**Comment by saziz0926** [comment]
Dear Martinpaljak,

We are happy to contribute commercially to your project.  I need some help
please.  When I ran gpj I get the following error.  I don't know where you
are resident but if you have sometime I can setup google hangouts meeting
and happy to pay for your hours.

D:\Downloads\gpj-20120310\gpj-20120310>java -version
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

D:\Downloads\gpj-20120310\gpj-20120310>java -jar gpj.jar -list
Found terminals: [PC/SC terminal Gemalto USB Smart Card Reader 0]
Found card in terminal: Gemalto USB Smart Card Reader 0
ATR: 3B 7F 96 00 00 80 31 80 65 B0 84 56 51 10 12 0F FE 82 90 00
DEBUG: Command  APDU: 00 A4 04 00 07 A0 00 00 01 51 00 00
DEBUG: Response APDU: 6A 82
Failed to select Security Domain GP211 A0 00 00 01 51 00 00 , SW: 6A 82
DEBUG: Command  APDU: 00 A4 04 00 08 A0 00 00 00 18 43 4D 00
DEBUG: Response APDU: 6F 65 84 08 A0 00 00 00 18 43 4D 00 A5 59 73 4A 06 07
2A 86 48 86 FC 6B 01 60 0C 06 0A 2A 86 48 86 FC 6B 02 02 01 01 63 09 06 07
2A 86 48 86 FC 6B 03 64 0B 06 09 2A 86 48 86 FC 6B 04 03 10 65 0B 06 09 2B
85 10 86 48 64 02 01 03 66 0C 06 0A 2B 06 01 04 01 2A 02 6E 01 02 9F 6E 06
12 91 53 56 02 00 9F 65 01 FF 90 00
Successfully selected Security Domain GemaltoXpressPro A0 00 00 00 18 43 4D
00
DEBUG: Command  APDU: 80 50 00 00 08 33 AD C1 54 EB B7 07 94
DEBUG: Response APDU: 4D 00 80 00 00 05 F4 E2 38 76 01 03 10 B2 28 82 A0 F1
A3 B3 73 2B 22 FE E4 B4 B5 2D D0 00 00 03 90 00
javax.smartcardio.CardException: Wrong initialize update response length.
        at
net.sourceforge.gpj.cardservices.GlobalPlatformService.openSecureChannel(Unknown
Source)
        at
net.sourceforge.gpj.cardservices.GlobalPlatformService.main(Unknown Source)

**Comment by martinpaljak** [comment]
Nice of you to offer commercial hours, but the trace is not from my software (and was from another software 7 years old at the time of posting). If you encounter the same issue with latest master of GPPro, please contact me via e-mail for paid hours.
