### ISSUE TITLE
Replace existing keys fix

### ISSUE THREAD

**Issue by MarkoDju** [martinpaljak/GlobalPlatformPro#184]
The tool currently enables you to change the existing key by not giving the _--new-keyver_ argument to _--lock-dek_, _--lock-mac_, _--lock-enc_, or to change to a new key with a new version, given by _--new-keyver_. You cannot change the key back to a previously used version.

For example:
1. we have a new card with factory keys, version 255
2. we change to a new set of keys, new version 1 (using _--lock-*** --new-keyver_ 1)
3. we change to a new set of keys, existing version 1 (using _--lock-***_ )
4. we change to a new set of keys, new version 2 (using _--lock-*** --new-keyver_ 2)
5. we want to change to a new set of keys, back to version 1 (using _--lock-*** --new-keyver_ 1) - we get an error: 0x6A80 (Wrong data/incorrect values in data).

I made some changes to the tool (new parameter _--replace-keyver_) so GPSession.putKeys(GPCardKeys keys, boolean replace) is correctly called with **replace=true**. Changed files (GPCommandLineInterface and GPTool) are in the attachment.
[gp.zip](https://github.com/martinpaljak/GlobalPlatformPro/files/3604483/gp.zip)

As I am currently trying to get Delegated Managment to work, I took a look at the putKey function and tried to add a replace feature also. But changing the APDU's P1 parameter to the version you want to change (as with DEK, ENC and MAC keys) gives me: PUT KEY failed: 0x6A86 Incorrect P1/P2  (I left the P2 parameter at 0x01). There should be an option to change the RSA key also.

**Comment by martinpaljak** [comment]
Some DWIM will be added around this into the next CLI version (no need to indicate replace, if key template contains the same key)

**Comment by martinpaljak** [comment]
This should be fixed by #220
