### ISSUE TITLE
Install method logic

### ISSUE THREAD

**Issue by Aiosa** [martinpaljak/GlobalPlatformPro#187]
What is the logic behind these lines in the install section?

1)
```
if (instcap.getAppletAIDs().size() <= 1) {
     calculateDapPropertiesAndLoadCap(args, gp, instcap);
}
```

Why would I want to load cap file if and only if the cap file contains up to one applet? What about those rare cap files that include more than one applet? The install mehod proceeds with `installAndMakeSelectable()` without loading the cap file onto card?

2)
```
if (args.has(OPT_FORCE) && (reg.getDefaultSelectedAID().isPresent() && privs.has(Privilege.CardReset))) {
      gp.deleteAID(reg.getDefaultSelectedAID().get(), false);
}
```
Why delete default selected applet in force mode if present? From the globalplatform documentation:
>Once the Card Reset privilege has been assigned to an Application, the privilege can be reassigned to a new Application either by deleting the Application which has the privilege, or by revoking its privilege.

The solution provided by GPPRo in not intuitive, at least in my opinion. While having in Readme:
> Force installation of applet.cap, deleting anything that's necessary, with AID information from the CAP:

the actual behaviour is that it deletes an applet even though it is not necessary - considering I want to have another applet as default selected, but want to keep the previous one nevertheless. This way I can lose all my data on the previous default selected applet. Wouldn't expect the install method to implicitly **delete** any applets that are from other packages (e.g. not performing re-install).

Thank you.

**Comment by martinpaljak** [comment]
1. That was a piece of code by a learning student, the logic of only installing (with -install) if the applet inside tha package can be automatically selected. If I missed that when reviewing, that's bad.
2. There are devices where you can't re-assign the privilege, only install with it. The fact that this will go on deleting possibly "unrelated" application should be made more clear.
3. The whole --default thing should probably be removed.

**Comment by martinpaljak** [comment]
To be precise, it was from GP2.1.1: 

Once the Default Selected privilege has been assigned to an Application, the privilege can only be
reassigned to a new Application by deleting the Application which has the privilege,
