### ISSUE TITLE
Error with use GlobalPlatformPro v0.3.10rc8-0-gf1dcf34

### ISSUE THREAD

**Issue by baharkhazan** [martinpaljak/GlobalPlatformPro#191]
Hi
I want to use new version of gpshell and download is from url "https://github.com/martinpaljak/GlobalPlatformPro/releases?after=v0.3.10rc9" when run this jar file in cmd return this error :
C:\gp\GlobalPlatformPro-master>java -jar gp.jar -info
 GlobalPlatformPro v0.3.10rc8-0-gf1dcf34
Running on Windows 7 6.1 amd64, Java 1.8.0_181 by Oracle Corporation
PC/SC failure: SCardGetStatusChange got response 0x6c6 (null: null)
I use older version of gpshell without any error. Why?
My reader is  ACS ACR1281 1S Dual Reader ICC 0 .
My card not Specific. 
My card support scp02

**Comment by martinpaljak** [comment]
a) this is not gpshell b) this is a transport layer issue. Try with a different driver (windows ccid vs vendor driver) or operating system (linux) or reader.
