### ISSUE TITLE
Help with ACOSJ smartcard

### ISSUE THREAD

**Issue by sergioszy** [martinpaljak/GlobalPlatformPro#193]
Hi,
I try to install applet in ACosJ 6 40k, but when I try to select default or select ISD, the response is
6D00,
If I try  gp -i and the response is

GlobalPlatformPro 19.06.16-0-gbaccf34
Running on Windows 10 10.0 amd64, Java 1.8.0_211 by Oracle Corporation
Reader: SCM Microsystems SCx35xx v2.0 USB SC Reader 0
ATR: 3B69000241434F534A76313031
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B69000241434F534A76313031

Could not SELECT default selected: 0x6D00 (Invalid INStruction)

The card in theory is empty.

Thanks in advance.

**Comment by martinpaljak** [comment]
Dup of #192
