### ISSUE TITLE
Weird response in listing applets with long AID-s

### ISSUE THREAD

**Issue by Erbah1m** [martinpaljak/GlobalPlatformPro#21]
Dear Martin, 

I create a package that contains 22 equal applets.(The applets are equal in program but different in AID.)
When I set the package AID and applet's AIDs as below, everything is OK. (I can install it and I can see them in the response of `gp -list` command)

>    Package AID = 0102030405
> 
>    App1  AID = 010203040501
>    App2  AID = 010203040502
>    App3  AID = 010203040503
>    App4  AID = 010203040504
>    App5  AID = 010203040505
>    App6  AID = 010203040506
>    App7  AID = 010203040507
>    App8  AID = 010203040508
>    App9  AID = 010203040509
>    App10 AID = 01020304050a
>    App11 AID = 01020304050b
>    App12 AID = 01020304050c
>    App13 AID = 01020304050d
>    App14 AID = 01020304050e
>    App15 AID = 01020304050f
>    App16 AID = 010203040510
>    App17 AID = 010203040511
>    App18 AID = 010203040512
>    App19 AID = 010203040513
>    App20 AID = 010203040514
>    App21 AID = 010203040515
>    App22 AID = 010203040516

Look : 

```
gp: gp -list
AID: A000000151000000 (|....Q...|)
     ISD OP_READY: Security Domain, Card lock, Card terminate, Default selected,
 CVM (PIN) management

AID: A0000001515350 (|....QSP|)
     ExM LOADED: (none)
     A000000151535041 (|....QSPA|)


gp: gp -install e:\PackageWithShortAIDs.cap

gp: gp -list
AID: A000000151000000 (|....Q...|)
     ISD OP_READY: Security Domain, Card lock, Card terminate, Default selected,
 CVM (PIN) management

AID: 010203040507 (|......|)
     App SELECTABLE: (none)

AID: A0000001515350 (|....QSP|)
     ExM LOADED: (none)
     A000000151535041 (|....QSPA|)

AID: 0102030405 (|.....|)
     ExM LOADED: (none)
     010203040507 (|......|)
     010203040506 (|......|)
     010203040505 (|......|)
     010203040504 (|......|)
     010203040503 (|......|)
     010203040502 (|......|)
     010203040501 (|......|)
     010203040513 (|......|)
     010203040512 (|......|)
     010203040511 (|......|)
     010203040510 (|......|)
     01020304050F (|......|)
     01020304050E (|......|)
     01020304050D (|......|)
     01020304050C (|......|)
     01020304050B (|......|)
     01020304050A (|......|)
     010203040516 (|......|)
     010203040515 (|......|)
     010203040514 (|......|)
     010203040509 (|......|)
     010203040508 (|......|)  
gp:
```

Now,I change I change the AID of Applets as below (everything else is the same as for before) :

>    Package AID = 0102030405
> 
>   App1  AID = 0102030405060708090001
>   App2  AID = 0102030405060708090002
>   App3  AID = 0102030405060708090003
>   App4  AID = 0102030405060708090004
>    App5  AID = 0102030405060708090005
>    App6  AID = 0102030405060708090006
>    App7  AID = 0102030405060708090007
>    App8  AID = 0102030405060708090008
>    App9  AID = 0102030405060708090009
>    App10 AID = 010203040506070809000a
>    App11 AID = 010203040506070809000b
>    App12 AID = 010203040506070809000c
>     App13 AID = 010203040506070809000d
>     App14 AID = 010203040506070809000e
>     App15 AID = 010203040506070809000f
>     App16 AID = 0102030405060708090010
>     App17 AID = 0102030405060708090011
>     App18 AID = 0102030405060708090012
>     App19 AID = 0102030405060708090013
>     App20 AID = 0102030405060708090014
>     App21 AID = 0102030405060708090015
>     App22 AID = 0102030405060708090016

In this case, I can load and install it. But I can't list my installed applets anymore!

```
gp: gp -list
AID: A000000151000000 (|....Q...|)
     ISD OP_READY: Security Domain, Card lock, Card terminate, Default selected,
 CVM (PIN) management

AID: A0000001515350 (|....QSP|)
     ExM LOADED: (none)
     A000000151535041 (|....QSPA|)


gp: gp -install e:\PackageWithLongAIDs.cap

gp: gp -list
javax.smartcardio.CardException: Get Status failed, SW: 6A88
        at pro.javacard.gp.GlobalPlatform.getConcatenatedStatus(GlobalPlatform.j
ava:1020)
        at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1070)
        at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:673)
        at pro.javacard.gp.GPTool.main(GPTool.java:499)
Exception in thread "main" javax.smartcardio.CardException: Get Status failed, S
W: 6A88
        at pro.javacard.gp.GlobalPlatform.getConcatenatedStatus(GlobalPlatform.j
ava:1020)
        at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1070)
        at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:673)
        at pro.javacard.gp.GPTool.main(GPTool.java:499)

gp:
```

Debug mode output : 

```
.
. 
.
A>> T=1 (4+0008) 80500000 08 E81EAC2B833E5DCF
A<< (0028+2) (70ms) 00004198001714974248FF0200B93785186688F163331EF41FA02CB8 900
0
Host challenge: E81EAC2B833E5DCF
Card challenge: 00B93785186688F1
Card reports SCP02 with version 255 keys
Master keys:
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F
Sequnce counter: 00B9
Derived session keys:
Version 0
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:1EC5FBCA9A5F21F727C14461A7D7E2C6
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:2688CFFD58CCF9EB52B5D5E786364C89
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:C181FE8094950965495E0D5023AFD65D
Verified card cryptogram: 63331EF41FA02CB8
Calculated host cryptogram: A269860A0E584230
A>> T=1 (4+0016) 84820100 10 A269860A0E5842301E0CBE71E485EA79
A<< (0000+2) (66ms) 9000
A>> T=1 (4+0010) 84F28000 0A 4F00DF01359AC330E966
A<< (0011+2) (46ms) 08A000000151000000019E 9000
A>> T=1 (4+0010) 84F24000 0A 4F003E447E78BC4DE5CC
A<< (0014+2) (45ms) 0B01020304050607080900070700 9000
A>> T=1 (4+0010) 84F22000 0A 4F00D20EAEA9E44363C1
A<< (0018+2) (48ms) 07A000000151535001000501020304050100 9000
A>> T=1 (4+0010) 84F21000 0A 4F003EA1383F26463052
A<< (0020+2) (54ms) 07A000000151535001000108A000000151535041 6310
A>> T=1 (4+0010) 84F21001 0A 4F002196E82C3A537F62
A<< (0000+2) (50ms) 6A88
javax.smartcardio.CardException: Get Status failed, SW: 6A88
        at pro.javacard.gp.GlobalPlatform.getConcatenatedStatus(GlobalPlatform.j
ava:1020)
        at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1070)
        at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:673)
        at pro.javacard.gp.GPTool.main(GPTool.java:499)
SCardEndTransaction()
SCardDisconnect("ACS CCID USB Reader 0", false)
Exception in thread "main" javax.smartcardio.CardException: Get Status failed, S
W: 6A88
        at pro.javacard.gp.GlobalPlatform.getConcatenatedStatus(GlobalPlatform.j
ava:1020)
        at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1070)
        at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:673)
        at pro.javacard.gp.GPTool.main(GPTool.java:499)

gp:
```

Is this a issue related to my card or it is related to the GlobalPlatformPro?

**Comment by martinpaljak** [comment]
For simplicity, please also make the .cap file(s) available

**Comment by ebramloder** [comment]
As the github prevent me to upload `.cap` file, I changed the extension to `.jpg` and then upload them.

![shortaids](https://cloud.githubusercontent.com/assets/7478826/7045731/f2acb166-de15-11e4-9a6a-f447147d553d.JPG)
![longaids](https://cloud.githubusercontent.com/assets/7478826/7045732/f2c656e8-de15-11e4-9f0f-f7a93b737cc5.JPG)

**Comment by ebramloder** [comment]
Dear Martin, 

Is there any solution for my issue? Is it related to the tool or it is a problem with my card?

**Comment by ebramloder** [comment]
Dear Martin,

 Shall I send something else (My project's code, for example)?

Kindly Regards.

**Comment by martinpaljak** [comment]
Yes, I could replicate a messed up card and according to specification (the way I read it) GPPro seems to be doing everything right, but the first generic suggestion here is NOT to send unverified/messed up code towards your cards. I'll keep the ticket open but don't expect activity on this.

**Comment by ebramloder** [comment]
Thank you.

FYI, In my case, when I send a package delete command, (i.e. `gp -delete 0102030405 -deletedeps`) everything goes fine again and the card is OK now. 

Kindly Regards.

**Comment by martinpaljak** [comment]
While the commands sent to the card have not changed significantly, you could try the latest master code, where applet listing is re-implemented.

**Comment by martinpaljak** [comment]
After giving it another look, all seems to be correct from GP APDU point of view, thus I do not believe there is anything I can do. Still a reminder: if you intentionally try to fsck up a card, you probably can find interesting corner cases. This software is not intended for testing those corner cases.
