### ISSUE TITLE
Lib can't be used in Android bellow 7 (API 24)

### ISSUE THREAD

**Issue by LeonardOneWave** [martinpaljak/GlobalPlatformPro#210]
We are trying to use GPPro library for eSE and BLE cards management on Android, mostly for internal tools but one of our potential clients is very interested as well. It works pretty fine on a recent Android device. However, some classes in GPPro are using ```Optional```, which is only available since Android 7 (API 24) : https://developer.android.com/reference/java/util/Optional, causing an error at runtime on devices running Android 6 and bellow, e.g. :
```
03-06 16:09:23.065  5741  5785 E AndroidRuntime: Process: io.onewave.android.onewave.testapp, PID: 5741
03-06 16:09:23.065  5741  5785 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Optional;
03-06 16:09:23.065  5741  5785 E AndroidRuntime:     at pro.javacard.gp.GPSecureChannel.valueOf(GPSecureChannel.java:21)
03-06 16:09:23.065  5741  5785 E AndroidRuntime:     at pro.javacard.gp.GPSession.openSecureChannel(GPSession.java:406)
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Optional" on path: DexPathList[[zip file "/data/app/io.onewave.android.onewave.testapp-1/base.apk"],nativeLibraryDirectories=[/data/app/io.onewave.android.onewave.testapp-1/lib/arm, /vendor/lib, /system/lib]]
...
Suppressed: java.lang.ClassNotFoundException: java.util.Optional
```

Nowadays, Android 6 still represents around 17% of running Android phones, according to this page : https://developer.android.com/about/dashboards. Thus we would like to support those phones too (incidentally, most of our QA phones are still running Android 6).

Would you be interested in a patch/PR for a better support on Android ? In this case, which approach would you prefer : a reimplementation of ```Optional``` in GPPro library (enventually with an adaptator in cli tool) or do not use ```Optional``` at all ? (Or any other solution we didn't though about).

**Comment by martinpaljak** [comment]
Have you seen the "sponsor" button of Github? ;)

GPPro does not target Android, and legacy Android-s, but JDK 1.8+ on the "backend". If you need to make it run on older Android, first recommendation would be to hack necessary workarounds in your app.

**Comment by LeonardOneWave** [comment]
We have plans to sponsor some open source projects that are useful for us. Your project is definitively on the short list. However, we're still relatively early stage and we'll need to raise money or start commercialisation before doing so.

The intended target of the project (JDK 1.8+) was the purpose of my question. I have implemented a workaround that works on Android (currently a reimplementation of Optional), and we maintain our version up to date with yours. Thus we were wondering if you might be interested or not. We're perfectly fine to stay like this. I thus close the bug.

Thanks a lot for your time and the work you've done !
