### ISSUE TITLE
Executing GlobalPlatformPro with flag `--version/-V` should not check for presence of a card

### ISSUE THREAD

**Issue by quapka** [martinpaljak/GlobalPlatformPro#217]
### Describe the bug
This bug is concerned only with the functionality of CLI utility not necessarily with card handling. (The `gp` is alias for `java -jar /path/to/gpjar` as described in README.) When executing the command `gp --version` or `gp -V` the tool checks for a presence of a card in a reader and if a card is not found it fails (return code is `1` and additional information `No smart card readers with a card found` is outputted.). 

### Information about your card
_Not relevant._

### Expected behavior
When running `gp --version` or `gp -V` the output should be similar to:
```
$ gp --version
GlobalPlatformPro v20.01.23-0-g5ad373b
Running on Linux 5.3.0-46-generic amd64, Java 1.8.0_252 by Private Build
```
And the return code should be `0` not matter if a card or reader has been found.

### Full log
_Not relevant._

### Additional context
None.

**Comment by martinpaljak** [comment]
Absolutely!

**Comment by quapka** [comment]
Great, thanks.
