### ISSUE TITLE
How to set the first ricv in the SCP02 unwrap function after e-a

### ISSUE THREAD

**Issue by ZYDuan** [martinpaljak/GlobalPlatformPro#218]
I try the 8_null_byte and the mac after e-a verify successfully. But both failed.
How to calculate the first ricv when verify the first response after e-a?

**Comment by martinpaljak** [comment]
Please follow https://github.com/martinpaljak/GlobalPlatformPro#contact

**Comment by ZYDuan** [comment]
**Describe the problem**
When  I try to calculate the R-MAC of the response APDU after e-a successfully, I always **verify R-MAC failed**. I don't know how to initialize  the first r-icv. As the log show, I set rMac to 80E610002010A00000000053594E4A4F4E4553535344000A53594E4A4F4E45530000000000 and r-ICV is full zero, but verify resp "006DFCFE5065740D309000" failed. The key of the ISD is 40~4F.
 
**Full log**
```
req:00A4040000
resp:6F108408A000000151000000A5049F6501FF9000
req:80502000084261A2F44EEC57EB00
resp:0000728314662294396620020046A58399EA65DDB9E2781A25689C719000
req:8482130010FAE81DD218F60A30A0F03ED2002B63B2
resp:9000
req:80E610002010A00000000053594E4A4F4E4553535344000A53594E4A4F4E45530000000000
resp:006DFCFE5065740D309000
```

**Comment by ZYDuan** [comment]
> Please follow https://github.com/martinpaljak/GlobalPlatformPro#contact



> **Describe the problem**
> When I try to calculate the R-MAC of the response APDU after e-a successfully by SCP02, I always **verify R-MAC failed**. I don't know how to initialize the first r-icv. As the log show, I set rMac to 80E610002010A00000000053594E4A4F4E4553535344000A53594E4A4F4E45530000000000 and r-ICV is full zero, but verify resp "006DFCFE5065740D309000" failed. The key of the ISD is 40~4F.
> I try to set rmac by icv after e-a, but also verified failed.
> 
> **Full log**
> 
> ```
> req:00A4040000
> resp:6F108408A000000151000000A5049F6501FF9000
> req:80502000084261A2F44EEC57EB00
> resp:0000728314662294396620020046A58399EA65DDB9E2781A25689C719000
> req:8482130010FAE81DD218F60A30A0F03ED2002B63B2
> resp:9000
> req:80E610002010A00000000053594E4A4F4E4553535344000A53594E4A4F4E45530000000000
> resp:006DFCFE5065740D309000
> ```

111

**Comment by martinpaljak** [comment]
This is not a globalplatformpro log.
