### ISSUE TITLE
SCP03: One Byte Counter "i"

### ISSUE THREAD

**Issue by klinz2050** [martinpaljak/GlobalPlatformPro#22]
Hi,
I'm a little bit confused about implementation of scp03_kdf. From my point of view, this function lacks implementation of byte counter i.

Section 4.1.5 of SCP03 Protocol
A 1 byte counter “i” as specified in the KDF (which may take the values '01' or '02'; value '02' is used
when “L” takes the values '00C0' and '0100', i.e. when the PRF of the KDF is to be called twice to
generate enough derived data).

I.e.
bo.write((lengthBits > 128) ? 0x02 : 0x01);

Best regards,
 klinz2050

**Comment by martinpaljak** [comment]
This is part of BC code: http://javadox.com/org.bouncycastle/bcprov-jdk15on/1.51/org/bouncycastle/crypto/params/KDFCounterParameters.html
