### ISSUE TITLE
No Selected ISD error

### ISSUE THREAD

**Issue by thotheolh** [martinpaljak/GlobalPlatformPro#23]
Hi, I am seeing a No selected ISD! error when running commands via Feitian smartcards and also using Feitian's card reader.

1.) Attempting to use list.
```
C:\>java -jar gp.jar -v -d -l
# Detected readers from SunPCSC
[ ] 0FTJC8 Virtual Card Reader 0
[ ] 0FTJC8 Virtual Ctless Reader 1
[ ] Unknown
[*] Feitian SCR301 0
SCardConnect("Feitian SCR301 0", T=*) -> T=0, 3B959640F001130A001D
SCardBeginTransaction("Feitian SCR301 0")
Reader: Feitian SCR301 0
ATR: 3B959640F001130A001D
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B959640F001130A001D

A>> T=0 (4+0000) 00A40400 00
A<< (0000+2) (2ms) 6A81
SCardEndTransaction()
SCardDisconnect("Feitian SCR301 0", false)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:
366)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)
```
2.) Attempting to set ISD AID
```
C:\>java -jar gp.jar -v -d -l --sdaid A000000003000000 --all
# Detected readers from SunPCSC
[ ] 0FTJC8 Virtual Card Reader 0
[ ] 0FTJC8 Virtual Ctless Reader 1
[ ] Unknown
[*] Feitian SCR301 0
SCardConnect("Feitian SCR301 0", T=*) -> T=0, 3B959640F001130A001D
SCardBeginTransaction("Feitian SCR301 0")
Reader: Feitian SCR301 0
ATR: 3B959640F001130A001D
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B959640F001130A001D

A>> T=0 (4+0008) 00A40400 08 A000000003000000 00
A<< (0000+2) (2ms) 6A81
SCardEndTransaction()
SCardDisconnect("Feitian SCR301 0", false)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:
366)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)
```
3.) Attempting to select ISD's AID instead of using --sdaid flag hoping to get something up
```
C:\>java -jar gp.jar -v -d -l --applet A000000003000000 --all
# Detected readers from SunPCSC
[ ] 0FTJC8 Virtual Card Reader 0
[ ] 0FTJC8 Virtual Ctless Reader 1
[ ] Unknown
[*] Feitian SCR301 0
SCardConnect("Feitian SCR301 0", T=*) -> T=0, 3B959640F001130A001D
SCardBeginTransaction("Feitian SCR301 0")
Reader: Feitian SCR301 0
ATR: 3B959640F001130A001D
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B959640F001130A001D

A>> T=0 (4+0000) 00A40400 00
A<< (0000+2) (2ms) 6A81
SCardEndTransaction()
SCardDisconnect("Feitian SCR301 0", false)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:
366)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)
```

**Comment by thotheolh** [comment]
I just tried to select the ISD domain manually via the APDU command as shown below and got 6A81 Function not supported.

C:\>java -jar gp.jar -d -v -a 00A404000800A00000000300000
0
# Detected readers from SunPCSC
[ ] 0FTJC8 Virtual Card Reader 0
[ ] 0FTJC8 Virtual Ctless Reader 1
[ ] certgate SmartCard microSD 1.0 0001 0
[*] Feitian SCR301 0
SCardConnect("Feitian SCR301 0", T=*) -> T=0, 3B959640F001130A001D
SCardBeginTransaction("Feitian SCR301 0")
Reader: Feitian SCR301 0
ATR: 3B959640F001130A001D
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B959640F001130A001D

A>> T=0 (4+0008) 00A40400 08 00A0000000030000 00
A<< (0000+2) (2ms) 6A81
A>> T=0 (4+0000) 00A40400 00
A<< (0000+2) (2ms) 6A81
SCardEndTransaction()
SCardDisconnect("Feitian SCR301 0", false)

**Comment by martinpaljak** [comment]
What makes you think this is a JavaCard in the first place?

**Comment by martinpaljak** [comment]
The other option is a card in incorrect lifecycle state

**Comment by thotheolh** [comment]
Hi,

This is a JavaCard as sold to me by Feitain. I have contacted my smart card
supplier and raised the issue as I also suspect it might have been an
incorrect lifecycle.

In the meantime I tested the tool on other smartcards (HSM smartcard tokens
using MPCOS 64K) and it reflects the same errors as well although I am
expecting these specially personalized cards to not have a selectable ISD ?

The Feitian JavaCard spec:
https://docs.google.com/spreadsheets/d/10s3dA_qGvWMajv8RhCWa00x-h-1Dx6SdF9rEKN-1RIg/edit#gid=952816161

The model is the FT-Java/C21C which is marketed to have JavaCard 2.2.2 and
GP 2.1.1 specs on it.

On Mon, Jun 22, 2015 at 12:14 AM, Martin Paljak <notifications@github.com>
wrote:

> The other option is a card in incorrect lifecycle state
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/martinpaljak/GlobalPlatformPro/issues/23#issuecomment-113921404>
> .
>



-- 
+---------------------------------------------------------+
 | PGP Secure Email Key ID:6FBFC19D |
+---------------------------------------------------------+

**Comment by martinpaljak** [comment]
I have the card (with same product name advertisement but a very different ATR) and it works OK (at least what comes to listing, loading etc) I suspect your card is in wrong lifecycle or otherwise broken. Ask your vendor.

**Comment by abdelhak-mes** [comment]
So, have you found a solution  ??!

**Comment by thotheolh** [comment]
Hi,

Apparently it is a smart card not properly configured into the OP_READY
state or do not support the ISD domain like certain proprietary smart cards
thus they are not ablento select ISD domain as it is not ready or
nom-existant

So, have you found a solution ??!

—
Reply to this email directly or view it on GitHub
<https://github.com/martinpaljak/GlobalPlatformPro/issues/23#issuecomment-167444109>
.

**Comment by abdelhak-mes** [comment]
everything worked fine, before I made some manipulations. I have A NXP JCOP 2.4.1.
There is no way to reconfigure it ? Or to set the ISD ?

Thx

**Comment by thotheolh** [comment]
Are you facing the same issue of not being able to select ISD ? What are
your circumstances and can you describe them ? For debug, run:

java -jar gp.jar -l -v -d

Copy and send the entire debug output if you can.

**Comment by abdelhak-mes** [comment]
Yeah, and there is the debug : 

# Detected readers from SunPCSC
[*] Gemplus USB Smart Card Reader 0
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BF71300008131FE4500C011E00C6F12AF
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3BF71300008131FE4500C011E00C6F12AF
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BF71300008131FE4500C011E00C6F12AF

A>> T=1 (4+0000) 00A40400 00
A<< (0000+2) (20ms) 6D00
SCardEndTransaction()
SCardDisconnect("Gemplus USB Smart Card Reader 0", false)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:366)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)

**Comment by martinpaljak** [comment]
If your card it not properly in READY state, refer to your vendor documentation on how to do that (or specify the correct ISD with --sdaid)

**Comment by abdelhak-mes** [comment]
There is what i have found : 
<isd>A0 00 00 00 03 00 00 00</isd>
<scp>02_15</scp>
<tp>T=0</tp>

**Comment by martinpaljak** [comment]
`gp -ldvi -sdaid A000000003000000` should then do the trick

**Comment by abdelhak-mes** [comment]
gp -ldvi -sdaid A000000003000000
Results : 

# Detected readers from SunPCSC
[*] Gemplus USB Smart Card Reader 0
SCardConnect("Gemplus USB Smart Card Reader 0", T=*) -> T=1, 3BF71300008131FE4500C011E00C6F12AF
SCardBeginTransaction("Gemplus USB Smart Card Reader 0")
Reader: Gemplus USB Smart Card Reader 0
ATR: 3BF71300008131FE4500C011E00C6F12AF
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BF71300008131FE4500C011E00C6F12AF

A>> T=1 (4+0008) 00A40400 08 A000000003000000 00
A<< (0000+2) (24ms) 6D00
***** Card info:
A>> T=1 (4+0000) 80CA9F7F 00
A<< (0045+2) (27ms) 9F7F2A4790503547910078330030380321939657274812304500000000081B4733323139330000000000000000 9000
Card CPLC:
ICFabricator: 4790
ICType: 5035
OperatingSystemID: 4791
OperatingSystemReleaseDate: 0078
OperatingSystemReleaseLevel: 3300
ICFabricationDate: 3038
ICSerialNumber: 03219396
ICBatchIdentifier: 5727
ICModuleFabricator: 4812
ICModulePackagingDate: 3045
ICCManufacturer: 0000
ICEmbeddingDate: 0000
ICPrePersonalizer: 081B
ICPrePersonalizationEquipmentDate: 4733
ICPrePersonalizationEquipmentID: 32313933
ICPersonalizer: 0000
ICPersonalizationDate: 0000
ICPersonalizationEquipmentID: 00000000
***** CARD DATA
A>> T=1 (4+0000) 80CA0066 00
A<< (0078+2) (37ms) 664C734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040215650B06092B8510864864020103660C060A2B060104012A026E0102 9000
GlobalPlatform card
Version: 2.1.1
TAG3: 1.2.840.114283.3
SCP version: SCP_02_15
TAG5: 1.3.656.840.100.2.1.3
TAG6: 1.3.6.1.4.1.42.2.110.1.2
***** KEY INFO
A>> T=1 (4+0000) 80CA00E0 00
A<< (0020+2) (22ms) E012C00401FF8010C00402FF8010C00403FF8010 9000
VER:255 ID:1 TYPE:DES3 LEN:16
VER:255 ID:2 TYPE:DES3 LEN:16
VER:255 ID:3 TYPE:DES3 LEN:16
Key version suggests factory keys
SCardEndTransaction()
SCardDisconnect("Gemplus USB Smart Card Reader 0", false)
Exception in thread "main" java.lang.IllegalStateException: No selected ISD!
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:366)
        at pro.javacard.gp.GPTool.main(GPTool.java:371)



What do you think, there is a hope ???

**Comment by thotheolh** [comment]
From this line:

"A>> T=1 (4+0008) 00A40400 08 A000000003000000 00
A<< (0000+2) (24ms) 6D00"

I think it failed to select the supplied ISD. Status Word with 6D00 means
the Instruction (INS) is not supported.

Before these errors occured, what were the actions you have taken
previously ?

You could also state the manufacturer and type of JavaCard you are using.

Without the ISD access, you wouldn't be able to do much to the card. Talk
to your card supplier about the problems with the debug.

**Comment by abdelhak-mes** [comment]
I don't have find any solution
thx.
