### ISSUE TITLE
AdoptOpenJDK not working with gp.exe

### ISSUE THREAD

**Issue by kategray** [martinpaljak/GlobalPlatformPro#230]
### Describe the bug

Attempting to use the latest release candidate's gp.exe with AdoptOpenJDK 8 (x64), it tells me I don't have a Java Runtime Environment.  I do.

### Expected behavior

Command runs.

### Full log
```
C:\Kate\JavaCard>java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

C:\Kate\JavaCard>gp
GlobalPlatformPro: This application requires a Java Runtime Environment 1.8.0
```

**Comment by martinpaljak** [comment]
This is a known issue with launch4j and adoptopenjdk and its windows registry keys. The next thing to do would be to move to the modules packaging. For now, run the jar with -jar. This I think is the closest about upstream: https://sourceforge.net/p/launch4j/bugs/197/

**Comment by kategray** [comment]
Thank you for that.  I was able to fix the issue after reading through the thread.

The trick is to check the Oracle Registry Keys, not just the JAVA_HOME keys.

![image](https://user-images.githubusercontent.com/2415200/86060040-8ff75d00-ba29-11ea-8ac6-5e22e1879345.png)

**Comment by kategray** [comment]
With the Oracle keys, it runs exactly as expected.

```C:\Kate\JavaCard>gp -V
#
# gp -V
# GlobalPlatformPro v20.06.19-0-g7fd1544
# Running on Windows 10 10.0 amd64, Java 1.8.0_252 by AdoptOpenJDK```

**Comment by martinpaljak** [comment]
Is a sufficient fix for this ticket to document this in README ?

**Comment by kategray** [comment]
That would certainly seem to fix the issue.  Thank you.

**Comment by kategray** [comment]
Amazon Corretto doesn't seem to have a solution yet, but if Launch4j accepts this PR, it should be:

https://github.com/mirror/launch4j/pull/9

**Comment by kategray** [comment]
Amazon Corretto sets the environment by default, when Setup environment is enabled.

```C:\Kate\JavaCard>gp -V
#
# gp -V
# GlobalPlatformPro v20.06.19-0-g7fd1544
# Running on Windows 10 10.0 amd64, Java 1.8.0_252 by Amazon.com Inc.```

**Comment by martinpaljak** [comment]
I'll keep this open until actually written into docs..

**Comment by martinpaljak** [comment]
Added this to Wiki: https://github.com/martinpaljak/GlobalPlatformPro/wiki/Getting-started#java
