### ISSUE TITLE
Does `gp --info` show the correct JavaCard version?

### ISSUE THREAD

**Issue by quapka** [martinpaljak/GlobalPlatformPro#234]
### Bug description
When executing `gp --info` I get `JavaCard v2` --- I am assuming, that this gives the version of JavaCard on the card (what else?). However, my custom applet, that calls `JCSystem.getVersion` function returns `0300`. I'm inclined to trust my applet. I have not dug into the GP code, I guess GP asks the card for this value, so maybe the card could be the culprit, sending an incorrect value. The code for the applet is pasted below. (I've double checked, that I'm using gp freshly build from `HEAD`).

### Information about the card
It is [Feitan A40](https://smartcard-atr.apdu.fr/parse?ATR=3B+FC+18+00+00+81+31+80+45+90+67+46+4A+01+00+20+05+00+00+00+00+4E)

Looking at the website I've noticed it says:
> The JavaCOS A40 java card is an implementation of the **Java Card 2.2.2** and Global Platform 2.1.1 specifications, running on the Infineon SLE77 platform.

Which might support, that my card has been mangled with and updated to Java Card 3.0, while the GP simply returns some factory value burned into the card (in this case `JavaCard v2` matches the 2.2.2 from the link).

### Expected behavior
I'd expect, that `gp --info` would return the same value as `JCSystem.getVersion`.

### Full log
Output from `gp --info -d -v `.

```bash
# GP_PATH=/home/qup/projects/fi/crocs/GlobalPlatformPro/gp.jar
# gp --info -d -v -i
SCardConnect("Alcor Micro AU9560 00 00", T=*) -> T=1, 3BFC180000813180459067464A01002005000000004E
# GlobalPlatformPro v20.07.04-2-gc360b3e
# Running on Linux 5.3.0-62-generic amd64, Java 1.8.0_252 by Private Build
A>> T=1 (4+0000) 00A40400 00 
A<< (0094+2) (29ms) 6F5C8408A000000003000000A550734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E01029F6501FF 9000
[DEBUG] GPSession - Auto-detected ISD: A000000003000000
A>> T=1 (4+0000) 80CA9F7F 00 
A<< (0045+2) (14ms) 9F7F2A4090779486AA6028012061011704104205374090610186AA610186AA6101000000000000000000000000 9000
CPLC: ICFabricator=4090
      ICType=7794
      OperatingSystemID=86AA
      OperatingSystemReleaseDate=6028 (2016-01-28)
      OperatingSystemReleaseLevel=0120
      ICFabricationDate=6101 (2016-04-10)
      ICSerialNumber=17041042
      ICBatchIdentifier=0537
      ICModuleFabricator=4090
      ICModulePackagingDate=6101 (2016-04-10)
      ICCManufacturer=86AA
      ICEmbeddingDate=6101 (2016-04-10)
      ICPrePersonalizer=86AA
      ICPrePersonalizationEquipmentDate=6101 (2016-04-10)
      ICPrePersonalizationEquipmentID=00000000
      ICPersonalizer=0000
      ICPersonalizationDate=0000 (2010-01-01)
      ICPersonalizationEquipmentID=00000000

A>> T=1 (4+0000) 80CA0042 00 
A<< (0000+2) (11ms) 6A88
[DEBUG] GPData - GET DATA(IIN): N/A
A>> T=1 (4+0000) 80CA0045 00 
A<< (0000+2) (11ms) 6A88
[DEBUG] GPData - GET DATA(CIN): N/A
Card Data: 
A>> T=1 (4+0000) 80CA0066 00 
A<< (0078+2) (20ms) 664C734A06072A864886FC6B01600C060A2A864886FC6B02020101630906072A864886FC6B03640B06092A864886FC6B040255650B06092B8510864864020103660C060A2B060104012A026E0102 9000
Tag 6: 1.2.840.114283.1
-> Global Platform card
Tag 60: 1.2.840.114283.2.2.1.1
-> GP Version: 2.1.1
Tag 63: 1.2.840.114283.3
Tag 64: 1.2.840.114283.4.2.85
-> GP SCP02 i=55
Tag 65: 1.3.656.840.100.2.1.3
Tag 66: 1.3.6.1.4.1.42.2.110.1.2
-> JavaCard v2
Card Capabilities: 
A>> T=1 (4+0000) 80CA0067 00 
A<< (0000+2) (11ms) 6A88
[DEBUG] GPData - GET DATA(Card Capabilities): N/A
A>> T=1 (4+0000) 80CA00E0 00 
A<< (0020+2) (15ms) E012C00401FF8010C00402FF8010C00403FF8010 9000
Version: 255 (0xFF) ID:   1 (0x01) type: DES3         length:  16 (factory key)
Version: 255 (0xFF) ID:   2 (0x02) type: DES3         length:  16 (factory key)
Version: 255 (0xFF) ID:   3 (0x03) type: DES3         length:  16 (factory key)

Warning: no keys given, defaulting to 404142434445464748494A4B4C4D4E4F
SCardDisconnect("Alcor Micro AU9560 00 00", true) tx:35/rx:251
```

### Additional context
The applet mentioned above:
```java
package com.jsec;

import javacard.framework.*;

public class JCVersion extends Applet {
    private static final byte INS_VERSION = 0x04;

    public static void install(byte[] array, short off, byte len) {
        new JCVersion().register();
    }

    public void process(APDU apdu) {
        if (selectingApplet()) {
            return;
        }

        byte[] buf = apdu.getBuffer();
        switch (buf[ISO7816.OFFSET_INS]) {
            case INS_VERSION:
                short version = JCSystem.getVersion();
                Util.setShort(buf, (short) 0, version);
                apdu.setOutgoingAndSend((short) 0, (short) 2);
                break;
            default:
                ISOException.throwIt(ISO7816.SW_INS_NOT_SUPPORTED);
        }
    }
}

```

**Comment by martinpaljak** [comment]
It shows what the card reports. This information is... informational. It often does not match what the card has been configured to. Leaving as-is with no intended changes.

**Comment by quapka** [comment]
Hmm, interesting, I suppose it is true for some of the other value as well? Might not be of huge importance, but is this documented somewhere? If not, maybe worth adding to the [Generic information](https://github.com/martinpaljak/GlobalPlatformPro#generic-information) part of the README.md?

**Comment by martinpaljak** [comment]
A lot has changed in the past few pre-releases and months and the releases are reaching a stage where a non-pre-release will happen. Big part of what is holding this back is documentation. It will be revised as much as the codebase has been.

As always, big part is on card vendors - you should talk to you vendor for accurate information, gp is just an "as-is" tool.

**Comment by quapka** [comment]
Cool, looking forward to it.
