### ISSUE TITLE
I2C support for Globalplateform commands

### ISSUE THREAD

**Issue by faboulous1** [martinpaljak/GlobalPlatformPro#235]
Generally speaking GP plateform java program works with Usb based smart card readers. But my question is that some Smart card does not provide ISO7816 USB reader interface, instead they support ISO 7816 (T=1) over I2C interface. We can find a USB that can work with Computer on one end and on other end translate the traffic to I2C, however my question is how to integrate GP java api so that it can communicate with USB and then over I2C to the smart card? Any ideas? Or any plans to integrate any such feature in GP? or may be i have missed some stuff, if it is already supported?

**Comment by martinpaljak** [comment]
You are free to implement a wrapper to whatever protocol or transport you want. You even don't need to change the binary distribution of GPPro, if you run it via apdu4j (sc gp ...). Documentation for that is unfortunately not existing yet.
