### ISSUE TITLE
Please use annotated tags for releases, so versions show up correctly

### ISSUE THREAD

**Issue by nickray** [martinpaljak/GlobalPlatformPro#243]
Hey,

I packaged this for Arch Linux and noticed that the version shown via `gp -V` comes from `git describe`, which only uses annotated tags (the last such is 19.06.16).

I fix this by overwriting your tag with an annotated tag during packaging (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=globalplatformpro#n22), so no urgency.

**Comment by martinpaljak** [comment]
Thanks! Fixed the release script (not in this repo)
