### ISSUE TITLE
Smartcard ATR Parser URL incorrect

### ISSUE THREAD

**Issue by kategray** [martinpaljak/GlobalPlatformPro#244]
### Describe the bug
The location of the Smart Card ATR parser site has changed, and does not forward to the new URL.

### Expected behavior

GlobalPlatform Pro links to the correct site on smartcard-atr.apdu.fr

For example, `https://smartcard-atr.apdu.fr/parse?ATR=3B8D0180FBA000000397425446590401CF`

### Full log
```
# Windows Hello for Business 1
Reader: Windows Hello for Business 1
ATR: 3B8D0180FBA000000397425446590401CF
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8D0180FBA000000397425446590401CF
```

### Additional context (from author's web site)
History
Since the beginning (in 2009) the Smart card ATR parsing service was hosted on Google App Engine. This is because the Google service is/was free of charge and was a new technology to discover.

...

Then I received an email from Google:
We’re writing to you to let you know that the legacy standalone App Engine SDK (appcfg) will be deprecated as of July 30, 2019, in favor of the Generally Available Google Cloud SDK (Cloud SDK).

You will need to migrate your projects off the legacy standalone SDK (appcfg) before the shutdown date of July 30, 2020. Projects included in this email will be whitelisted to use the legacy standalone SDK (appcfg) until July 30, 2020, but any new projects will not be able to use the legacy standalone SDK (appcfg) from July 30, 2019.

... 

The solution was to host the ATR parsing service myself.

**Comment by martinpaljak** [comment]
Thanks for the report!

Actually I have decided to remove this link altogether since 6347f0f5dc7eff1a48c22d498dc8007c8a0ff995

It is included (together with local parsing) in apdu4j https://github.com/martinpaljak/apdu4j/blob/master/tool/src/main/java/apdu4j/ATRList.java
