### ISSUE TITLE
GPPro now fails for applet reinstall one-liner

### ISSUE THREAD

**Issue by ph4r05** [martinpaljak/GlobalPlatformPro#251]
### Feature request
Previous versions of GPPro enabled to reinstall an applet in the following way:
```
gp --delete PACKAGE_AID --install applet.cap
```

The GPPro `globalplatformpro:20.08.12` fails.
- `--delete PACKAGE_AID` fails if there is an applet installed in the package, so now we have to call `--delete APPLET_AID --delete PACKAGE_AID` before installing the applet
- `--delete APPLET_AID --delete PACKAGE_AID --install applet.cap` fails if there is a single deletion error, so the currently only way (I can think of) to make it work properly from scripts is to call GPPro 3 times:

```
gp --delete APPLET_AID
gp --delete PACKAGE_AID
gp --install applet.cap
```

I was thinking whether there is a simple way of reinstalling the applet without either listing applets and removing all deps manually or without calling `--delete` on everything and ignoring the result. 

The idea is to use it in scripts (bash, gradle plugins) without adding complicated logic on applet removal when we just need to reinstall the applet. 

Would it be maybe possible to add `--reinstall` switch that would do the removal logic? 
Or adding something like `--ignore-delete-error` that would ignore the error and proceed with the `--install` correctly?

Thanks for the suggestions.

**Comment by martinpaljak** [comment]
Does this relate to #142 ?

**Comment by ph4r05** [comment]
> Does this relate to #142 ?

The command returns the exit code properly, so I would say it is not related.

**Comment by ph4r05** [comment]
Potential workaround for reinstall one-liner
```
gp --uninstall applet.cap --install applet.cap
```
