### ISSUE TITLE
gp.exe --info 

### ISSUE THREAD

**Issue by veso266** [martinpaljak/GlobalPlatformPro#266]
### Describe the bug
I am trying to play with gp.exe --info command and get 
```
Could not SELECT default selected: 0x6E00 (Invalid CLAss)
```

### Information about your card
I don't know its a SIM card nothing is written on it exept a logo and this: https://smartcard-atr.apdu.fr/parse?ATR=3B3F95008069AF033D00C60000000E831E9F16

doesn't show anything 

### Expected behavior

Am what ever --info command outputs, I guess info about card reader, card vendor, etc

### Full log
Re-run your command with `-d -v -i` switches and:

```
GlobalPlatformPro v20.01.23-0-g5ad373b
Running on Windows 7 6.1 amd64, Java 11.0.5 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] Gemalto USB Key Smart Card Reader 0
SCardConnect("Gemalto USB Key Smart Card Reader 0", T=*) -> T=0, 3B3F95008069AF033D00C60000000E831E9F16
SCardBeginTransaction("Gemalto USB Key Smart Card Reader 0")
Reader: Gemalto USB Key Smart Card Reader 0
ATR: 3B3F95008069AF033D00C60000000E831E9F16
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B3F95008069AF033D00C60000000E831E9F16

A>> T=0 (4+0000) 00A40400 00 
A<< (0000+2) (85ms) 6E00

```

**Comment by martinpaljak** [comment]
Your card is not a "standard" global platform card (as defined by global platform card spec)

**Comment by veso266** [comment]
Am, what kind of card is it then, its a SIM Card from a defunct mobile operator, and as well as I am aware SIM cards should support java applets, please correct me if I am wrong 😀

**Comment by martinpaljak** [comment]
as you said - it is a SIM card. If it does support applets, then that would probably be covered by OTA service keys. That method is not supported by GPPro. See #91 and #253 for some background
