### ISSUE TITLE
Unable to access jarfile gp.jar

### ISSUE THREAD

**Issue by Bianca988** [martinpaljak/GlobalPlatformPro#289]
Hello,

I did everything that was mentioned and when I try to use the first command with gp: java -jar gp.jar -info I receive the following error : Error: Unable to access jarfile /home/bianca/GlobalPlatformPro/gp.jar. 
I am quite a beginner here so maybe I did something wrong but I spent quite a few days on this and I would really appreciate some help.
See complete log bellow : 

<img width="941" alt="image" src="https://user-images.githubusercontent.com/64011826/157230679-eab414b8-541c-46c6-92c7-a14d72982d36.png">

Thank you!

**Comment by martinpaljak** [comment]
if you build from source the jarfile is placed in tool/target/gp.jar, thus "java -jar tool/target/gp.jar" is what you need to issue.
