### ISSUE TITLE
Deletion not allowed. Some app still active? - is it possible to delete a package or an applet

### ISSUE THREAD

**Issue by venkateshkumartvk** [martinpaljak/GlobalPlatformPro#300]
Hi

I have been programming with GP and I guess i have some issues while uninstalling an applet. When I try to delete/ force delete the applet I get the error message "Deletion not allowed. Some app still active?" 

I have tried to remove the package, which also results with the same response (status word 6F00 & 6985). The applet is in SELECTABLE state and continues to work. Is there anyway I can remove this applet/ package from the card ? I understand there might be some dependencies hanging in the card somewhere, but dont know how to identify and fix it.  

Any pointers would help. Thanks in advance
Venks

**Comment by venkateshkumartvk** [comment]
Wow, thats a quick response, thanks. This is a GP v 2.2. Is there any other way to find if it supports delete or not ?

**Comment by martinpaljak** [comment]
Will you provide a full log of the issue (with -ldvi added) ?

**Comment by martinpaljak** [comment]
Stale.
