### ISSUE TITLE
zsh: command not found: gp

### ISSUE THREAD

**Issue by HaoYu-Chuang** [martinpaljak/GlobalPlatformPro#302]
### Describe the bug
I use macOS terminal and follow the download steps:
1. git clone https://github.com/martinpaljak/GlobalPlatformPro
2. cd GlobalPlatformPro
3. mvn package (build success)
4. ant
the result of the command "ant" is "Buildfile: build.xml does not exist! Build failed"
and I try to input "gp" but getting the result "zsh: command not found: gp"

Which step was done wrong or missed?

thank you!

**Comment by martinpaljak** [comment]
Latest README does not describe this. You should be using tool/target/gp.jar and thus `java -jar tool/target/target gp.jar`
