### ISSUE TITLE
Fix latest release links on the project website https://javacard.pro/globalplatform/

### ISSUE THREAD

**Issue by quapka** [martinpaljak/GlobalPlatformPro#303]
This issue is on https://javacard.pro/globalplatform/ not with GlobalPlatformPro directly.

### Describe the bug
The linked [website](https://javacard.pro/globalplatform/) in the project description contains download links to the latest releases:
https://github.com/martinpaljak/GlobalPlatformPro/releases/latest/gp.exe
https://github.com/martinpaljak/GlobalPlatformPro/releases/latest/gp.jar

However, those links return `404` and `Not Found`.

### Expected behavior

The valid links are (notice the extra `/download/` part):
https://github.com/martinpaljak/GlobalPlatformPro/releases/latest/download/gp.exe
https://github.com/martinpaljak/GlobalPlatformPro/releases/latest/download/gp.jar

**Comment by martinpaljak** [comment]
Is that separate page worth the trouble at all? Maybe make it redirect to Github.. ?

**Comment by quapka** [comment]
Do you mean whether [javacard.pro/globalplatform](https://javacard.pro/globalplatform) is worth the trouble? I am not the one making the call, but removing it and linking straight to GitHub sounds reasonable.

**Comment by martinpaljak** [comment]
Thanks for reporting, fixed!
