### ISSUE TITLE
IllegalArgumentException when using CLI

### ISSUE THREAD

**Issue by nic1v** [martinpaljak/GlobalPlatformPro#307]
Hello, 

I'm receiving this IllegalArgumentException when running any command through Windows CLI...

Currently using this Reader/Writer + Card set but no FOBs though (https://dangerousthings.com/product/acr122u/)

Let me know if there is more information I can provide!

```
C:\Users\Nic\Downloads>gp -info -d -v -i
GlobalPlatformPro v20.01.23-0-g5ad373b
Running on Windows 10 10.0 amd64, Java 19.0.2 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] ACS ACR122 0
SCardConnect("ACS ACR122 0", T=*) -> T=1, 3B8F8001804F0CA000000306030001000000006A
SCardBeginTransaction("ACS ACR122 0")
Reader: ACS ACR122 0
ATR: 3B8F8001804F0CA000000306030001000000006A
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8F8001804F0CA000000306030001000000006A

A>> T=1 (4+0000) 00A40400 00
SCardEndTransaction("ACS ACR122 0")
SCardDisconnect("ACS ACR122 0", true) tx:0/rx:0
Exception in thread "main" java.lang.IllegalArgumentException: newPosition < 0: (-2 < 0)
        at java.base/java.nio.Buffer.createPositionException(Buffer.java:344)
        at java.base/java.nio.Buffer.position(Buffer.java:319)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1526)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:267)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmitImpl(Smartcardio.java:807)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmit(Smartcardio.java:688)
        at apdu4j.terminals.LoggingCardTerminal$LoggingCard$LoggingCardChannel.transmit(LoggingCardTerminal.java:254)
        at apdu4j.CardChannelBIBO.transceive(CardChannelBIBO.java:22)
        at apdu4j.APDUBIBO.transmit(APDUBIBO.java:36)
        at pro.javacard.gp.GPSession.discover(GPSession.java:127)
        at pro.javacard.gp.GPTool.main(GPTool.java:237)
```

**Comment by martinpaljak** [comment]
- acr122 is one of the worst readers to use (many knockoffs and variations)
- you get zero bytes of data from the reader for some reason. Can you try another card/another reader?
- i suspect this is because you try to use GPPro with a Mifare card, which makes little sense. https://smartcard-atr.apdu.fr/parse?ATR=3B8F8001804F0CA000000306030001000000006A

**Comment by martinpaljak** [comment]
Actually this can be improved to throw a meaningful exception when the reponse is less than 2 bytes in length.

**Comment by nic1v** [comment]
Hello Martin! Thanks for the response. 

I think the one card I was using was a Mifare card ([Bought From Here](https://www.amazon.com/ETEKJOY-ACR122U-13-56MHz-Contactless-Writable/dp/B07FCLY4S9))

I also tried this with a different card (NFC Ring actually) with the same response...
```
C:\Users\Nic\Downloads>gp -info -d -v -i
GlobalPlatformPro v20.01.23-0-g5ad373b
Running on Windows 10 10.0 amd64, Java 19.0.2 by Oracle Corporation
# Detected readers from JNA2PCSC
[*] ACS ACR122 0
SCardConnect("ACS ACR122 0", T=*) -> T=1, 3B8F8001804F0CA000000306030001000000006A
SCardBeginTransaction("ACS ACR122 0")
Reader: ACS ACR122 0
ATR: 3B8F8001804F0CA000000306030001000000006A
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B8F8001804F0CA000000306030001000000006A

A>> T=1 (4+0000) 00A40400 00
SCardEndTransaction("ACS ACR122 0")
SCardDisconnect("ACS ACR122 0", true) tx:0/rx:0
Exception in thread "main" java.lang.IllegalArgumentException: newPosition < 0: (-2 < 0)
        at java.base/java.nio.Buffer.createPositionException(Buffer.java:344)
        at java.base/java.nio.Buffer.position(Buffer.java:319)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1526)
        at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:267)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmitImpl(Smartcardio.java:807)
        at jnasmartcardio.Smartcardio$JnaCardChannel.transmit(Smartcardio.java:688)
        at apdu4j.terminals.LoggingCardTerminal$LoggingCard$LoggingCardChannel.transmit(LoggingCardTerminal.java:254)
        at apdu4j.CardChannelBIBO.transceive(CardChannelBIBO.java:22)
        at apdu4j.APDUBIBO.transmit(APDUBIBO.java:36)
        at pro.javacard.gp.GPSession.discover(GPSession.java:127)
        at pro.javacard.gp.GPTool.main(GPTool.java:237)
```

Is there a Reader/Writer you suggest? I'm currently trying to learn about this all to make an access control system for my house as a hobby so I appreciate any advice!

**Comment by martinpaljak** [comment]
https://github.com/fidesmo/fdsm/wiki/Choosing-a-desktop-reader - from the affordable/chinese ones i prefer 1252 myself.

**Comment by martinpaljak** [comment]
Try with your contactless bank card.

**Comment by jo-bitsch** [comment]
I was wondering if the error message could be further improved to indicate, that if the response is zero bytes long, this might be a card didn't transact in time issue.

I ran into a little annoyance, where the install command on the (NFC connected) smartcard inside the following code takes more than 4 seconds with an acr122:
https://github.com/martinpaljak/GlobalPlatformPro/blob/a8897e5d84a36c1ff730a212cd31aa744e722a17/library/src/main/java/pro/javacard/gp/GPSession.java#L901-L903

Now, I understand that this is really not GlobalPlatformPro's fault at all and in the end I got it to work by using a different reader that had a different maximum timeout for the card to transact. (Actually, I used https://f-droid.org/en/packages/com.vsmartcard.remotesmartcardreader.app/ and my phone and just set the timeout to 30s, the transaction took about 4.5s)

It would have saved me more time than I really would like to admit, if the error message had already included that the card probably didn't transact in time and what the time actually was.

Thanks though, for your really excellent tool!

**Comment by martinpaljak** [comment]
ACR122(U) is still a “broken, not supported reader”. See https://github.com/martinpaljak/NFC4PC/wiki/Supported-readers for a non-conclusive list of contactless readers I regularly use/test.

The reason for empty responses could be a timeout with some reader firmware or it could be “cosmic rays” or something else.

If any code should be added, it would be a fat warning based on a regexp matching the reader name at the very beginning of the tool, saying “THIS READER IS NOT SUPPORTED, CONTINUE AT YOUR OWN RISK”.

**Comment by martinpaljak** [comment]
@jo-bitsch  You should get a timing also for exceptions with the latest version, IIRC? If not, then that is something to be fixed.

**Comment by jo-bitsch** [comment]
With GlobalPlatformPro f2af9ef downloaded from https://github.com/martinpaljak/GlobalPlatformPro/releases/tag/v24.10.15, which is currently marked as latest,
the last lines of the output look like this:

```
$ gp.jar -dvl --key $KEY --force --install myapplet.cap
[...]
A<< (0048+2) (58ms) E3154F05A0000006479F7001018408A0000006472F0001E3174F07A00000015153509F7001018408A000000151535041 9000
A>> T=1 (4+0010) 84F22002 0A 4F008AB0D403A0E37A4B 00
A<< (0028+2) (49ms) E30B4F05A0000006479F700101E30D4F07A00000015153509F700101 9000
A>> T=1 (4+0038) 84E60C00 26 05A00000064708A0000006472F000108A0000006472F0001010002C900002B509329B74B8F8D 00
Invalid argument: newPosition < 0: (-2 < 0)
# SCardEndTransaction("ACS ACR122U PICC Interface 00 00")
# SCardDisconnect("ACS ACR122U PICC Interface 00 00", false) tx:33296/rx:821 in 49s520ms
```

So, for the previous (successful) APDU transfer, I see the timing information. For the final (failing) one, there is just the error from `java.nio.Buffer.position()` which I think is caused by

https://github.com/martinpaljak/apdu4j-jnasmartcardio/blob/23a58f2ab46897f766c62e6fb780d78aac5d439d/src/main/java/jnasmartcardio/Smartcardio.java#L886


Did I miss a newer pre-release or some additional command argument?

From the linked commit https://github.com/pyhoon/apdu4j/commit/c98e592b19730817bda2c032acb375fb6135d784 I would have thought, there might be a message such as `Broken incoming data` but I don't see any of that in my output.

I understand, that this particular reader is unsupported, though and this really is not the fault of GlobalPlatformPro at all.

I would really appreciate you adding timing info for the next person running into this though.

**Comment by martinpaljak** [comment]
@jo-bitsch The apdu4j repo you referenced I have no idea about. But I will look into it, as I also want to add totals around SCardTransmit (and make sure exceptions are properly logged with timing as well). See https://github.com/martinpaljak/apdu4j/issues/93
