### ISSUE TITLE
gp.jar contains duplicate file entries under /META-INF

### ISSUE THREAD

**Issue by dkartaschew** [martinpaljak/GlobalPlatformPro#33]
Have found that the pre-built gp.jar file has duplicate file entries under `/META-INF/maven/net.sf.jopt-simple/jopt-simple/` which is causing some Maven builds to fail.

We currently use GlobalPlatformPro embedded in a larger application, and use Maven to handle the build process for the application. We sign all jars with our code signing keys via the `maven-jarsigner-plugin`, and during the phase in which it removes existing signatures on application dependencies, it fails on the gp.jar file as it contains multiple file entries under the above specified path.

Recommended fix would be to remove `/META-INF/maven` folder/directory from the gp.jar as it's not needed for gp.jar to work and would solve the jar signing issues as well.

**Comment by martinpaljak** [comment]
If you use a larger application, I assume you don't use the command line tool, thus maybe you want to use the "bare" jar, which is named "openkms-gp.jar" ?

**Comment by dkartaschew** [comment]
Hi Martin, 
Happy to use the openkms-gp.jar, however would like to confirm that they only required dependencies are adpu4j and jnasmartcardio.

**Comment by martinpaljak** [comment]
Also BouncyCastle. But I'll see how to get rid of the unwanted maven artefacts.

**Comment by martinpaljak** [comment]
I'll make a release containing this fix shortly.
