### ISSUE TITLE
Command line option "production"

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#36]
Ensures that no sensitive information - e.g., OP keys are displayed or in logs. OP keys could be replaced with KCV values allowing audit.

**Comment by martinpaljak** [comment]
The sensible solution IMHO would be to have normal debugging on debug level and keyset providers to log key material only on trace level. Also, a specialized SessionKeyProvider might be an option. As a general rule, if master keys need to be protected, a HSM is supposed to be used with a dedicated SessionKeyProvider. Providing a universal PKCS#11 based SessionKeyProvider is planned, but somewhat meaningless for a command line client.

**Comment by dancvrcek** [comment]
yeap, I think it's a reasonable approach - "trace" or "finest" level for sensitive stuff. A cmd line switch would then only check that debug level is higher than the "finest".

**Comment by martinpaljak** [comment]
So my conclusion is to be "production capable" from command line by default with the option to become verbose. Would that be OK? The idea is to not be "explicitly correct if asked but not correct unless asked to" but vice versa. DWIM. And to keep the number of command line options to a comprehensible number.

**Comment by martinpaljak** [comment]
v0.4 will invalidate this case, I hope.
