### ISSUE TITLE
Dual control

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#37]
"dualcontrol" - that will allow entering and reconstructing OP keys from components (2 or 3).

**Comment by martinpaljak** [comment]
PR-s with a specialized SessionKeyProvider are welcome. For a command line utility they don't really make sense, as the plaintext key material would be present within a context of a JVM anyway.

**Comment by dancvrcek** [comment]
ok, will do. The problem is not that much what is in the memory - we can take care of that by erasing/burning/dissolving/... of the whole thing when we finish. But we need to be able to enter keys without compromising chain of custody and keys.

**Comment by martinpaljak** [comment]
I don't think that adding support for key construction (from components) to the internal API or command line tool would make sense. Eventually the API requires "plaintext keys" or at least something that can calculate session keys (like the SessionKeyProvider interface is intended to do). Relying on some other library or custom provider that would give the keys (and adding support for them from command line) would make sense, as would improvements for the (quite quick'n'dirty) SessionKeyProvider interface.

Thus I can only think of two action items from this feature request:
- ability to specify (custom and/or pre-existing) "session key providers" with implementation from the command line (class, jar etc, much like the request for custom javax.smartcardio providers), for what currently only a "plaintext key provider" exists (I plan to add a PKCS11SessionKeyProvider as well once I figure out a usable way to parametrize it)
- more flexible and thoughtful interface for SessionKeyProvider, if necessary. Also more careful handling of session key material might be a nice to have feature, but for *real life* use you better have proper operational procedures that guarantee the safety of the key material on the plaintext host machine.

**Comment by dancvrcek** [comment]
Sorry for the delay but a difficult week+ ...  I guess that ability to specify session key providers would be a nice flexible approach. Are you thinking on the level of GPKeySet or GPKey?

We are not that interested in OP related stuff - nor tinkering with it - but only with the source of keys / their creation.

It seems to me that SessionKeyProvider is a bit too close to OP. On the other hand - a new parameter to getSessionKeys() - with a pointer to a class instance / null = staticKeys could work.

**Comment by martinpaljak** [comment]
Not sure what you mean with OP here. SessionKeyProvider essentially gives *session keys* for a specific session, which means deriving them as necessary from master keys, which in turn can come from wherever - a HSM or config file or ... Requires a bit of coding but should cover all needs.

**Comment by dancvrcek** [comment]
OP - open platform - not sure if it's a good acronym for this. OK, so what is your current idea for implementing this? We will need it pretty soon so I'm happy to do an initial implementation.

**Comment by martinpaljak** [comment]
SessionKeyProvider is a bit close to OP, but the idea is to use master key(s) in a HSM, thus the need to emit things that can live outside of a HSM and these are session keys.

What about a `-key-provider jar:class:arg` that is supposed to implement SessionKeyProvider and you can take the current PlaintextKeyProvider and implement a GUI you want, like constructing the key from different components ?

**Comment by martinpaljak** [comment]
The idea is to have plugins, (`-plugin some.jar`) that register key providers (or other plugins, soon about that). For command line, unless you specify plaintext keys (with the current `-key/-kcv/-emv/-visa2` for master key based per-card derived keys, or `-key-enc/-key-dec/-key-mac` for pre-calculated keys) there will be a third option, which will be `-keys provider:args`.

Main reason for this change is: 1) hardware backed master keys 2) connectivity to key management systems 3) replacing the "tested cards" wiki mess with and online service, that knows how to access once tested cards from public sources.

Please have a look after 0.4, suggestions for interface improvements (both Java and CLI) shall be most welcome.
