### ISSUE TITLE
Missing "configure" script or prerequisites list

### ISSUE THREAD

**Issue by ferrieux** [martinpaljak/GlobalPlatformPro#371]
The project is awesome, but the very first step, installing the prerequisites, is mysterious, as there is no "configure" script and the provided Makefile doesn't work out of the box (obviously needing a `$JAVA_HOME`, some version of jre, and possibly dozens of other dependencies).

The intended population here is telecom-savvy people who just don't eat and sleep with *java* ;)

One way to help beginners is to automate (with a `./configure` or `make prereq` or similar script).

Another is to document ("please install JRE version >=X and set JAVA_HOME to ...")

**Comment by martinpaljak** [comment]
There's a link to the wiki on the main readme, which clearly states how this should be run. https://github.com/martinpaljak/GlobalPlatformPro/wiki/Getting-Started#java

The makefile exists purely for personal use, to be honest. If you don't do Java development, you're probably after the pre-built .jar file, so the presence of a makefile (or god forbid an autoconf script) is somewhat irrelevant?

**Comment by martinpaljak** [comment]
Also, I should probably add this to the FAQ: https://github.com/martinpaljak/GlobalPlatformPro/issues/293

The intended audience is not telecom (in fact working with SIM cards is not a goal and requires a lot more effort than "traditional" smart cards for PKI-alike purposes)
