### ISSUE TITLE
GPKeySet.toString() - ability to disable printing the whole key value

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#42]
It would be quite useful if we were able to just print the string without the "Value".

**Comment by dancvrcek** [comment]
... thinking about it - it could actually be done in a custom key manager. Possibly enabled the same way is "terminals" ?

**Comment by martinpaljak** [comment]
Correct. The only remaining key provider in open source shall be PlaintextKeys, which, as the name implies, handles plaintext keys. Even then, key material is only logged if trace level is enabled (-d).

GPKeySet is no more, there is GPSessionKeyProvider abstract class, which explicitly states, that *session keys* (vs card keys) are always ephemeral in nature and handled in plaintext and GPKey (which contains plaintext key values) and a sample for working with plaintext keys.

Key material is only logged in trace level (enabled with -d)
