### ISSUE TITLE
the new "terminals" option not in the README.md yet

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#43]
:)

**Comment by martinpaljak** [comment]
Indeed. There will be another hard-to-document option of "-keys" that supports custom key providers (PKCS#11, proprietary card key derivation algorithms etc)

**Comment by martinpaljak** [comment]
terminals option has been removed. For a flexible CLI-based approach to transport layers, apdu4j can be used (prefix "gp" with "apdu4j" to use any transport plugin from apdu4j)
