### ISSUE TITLE
--bs option re-written by SELECT FCI

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#46]
I think this needs a bit of a re-think. There are 2 aspects of the command length:
1. what smartcard supports - FCI
2. format of T=1 and efficient communication - the max Length of T=1 TPDU is 254B - this includes CLA INS P1 P2 Le. If it's longer, the reader will start chaining and there are additional message exchanges between reader and smartcard to transfer a few remaining bytes.

**Comment by dancvrcek** [comment]
as a quick fix....

GlobalPlatform.java - l. 291 (or thereabout)
if (bs > 255) {
   logger.debug("Ignoring auto-detected block size " + bs);
}
.....

could be changed to:
if (bs > this.blockSize)

**Comment by martinpaljak** [comment]
Correct, it is a very quick hack and definitely not uniformly implemented

**Comment by martinpaljak** [comment]
The whole block size handling needs a rework but this specific thing should be fixed.
