### ISSUE TITLE
--force to solve installation failures automatically?

### ISSUE THREAD

**Issue by user8547** [martinpaljak/GlobalPlatformPro#47]
Some --force flag would be useful which could handle failures automatically.

For example: `java -jar gp.jar --force -install applet.cap -default`
could remove previous applet if it is already on the card and if there is some other applet with -default privilege then it would also be removed.

**Comment by martinpaljak** [comment]
Good idea, I've been thinking about a similar option (when removing the "--deletedeps" option) but then I though that maybe it is helpful to require explicit long options. 

One thing I thought about was making some options work only if the key material is the default test key 40..4F but would require extra steps otherwise

**Comment by dancvrcek** [comment]
Hi guys, I'm not sure about different behaviour for default and other keys. If someone has an application or script that could potentially break if the key is changed then it makes integration and testing much more difficult.

-force could work for me if it only deletes the applet I'm trying to install. I'm not sure about the -default - it starts being a bit dangerous :)

**Comment by user8547** [comment]
This is what you would expect when using the term "force". The command is completed successfully what ever that takes.

Without --force, I have to --list, note down the AID, execute --delete AID and then my command again. Not nice if I have few cards on which I want to test the applet.

**Comment by martinpaljak** [comment]
If you could please try the master and see if it works for you. Thanks for the push, I had planned it for a while ;)

**Comment by dancvrcek** [comment]
works well for me!

.... and as a bonus annoying warnings about unknown FCI tags disappeared from our logs :)
