### ISSUE TITLE
handling of many smart cards

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#48]
We are currently using Python scripts to do that but it means that we are spawning that many JVMs and have been having some issues with memory ... :o 

I have no idea at the moment how to do it but would it be possible to run one instance of gp.jar and send to it commands identified with terminal names?

**Comment by martinpaljak** [comment]
You can control the memory consumption of JVM with parameters.

What shall disappear is the --all brainfart and more sensible handling of multiple connected readers. Everything else should be handled by a custom Java application, I don't intend to expand GPTool to do anything but be a command line utility.

**Comment by dancvrcek** [comment]
:) Indeed we can but the overhead of launching a JVM for 1-2 commands is quite significant.

Fair enough. I guess the most sensible approach is to build a daemon on top of gppro. I wonder - would you be at all happy to move the main() code into a method of the GPTool class that would get args or argv as a parameter?

That way, we could just use the GPTool class from another class.

**Comment by martinpaljak** [comment]
GPTool.java internals is waiting for a split and refactoring, but that will happen after the SSD code is functionally complete.

**Comment by martinpaljak** [comment]
Maybe the simple split shall happen earlier, next week or so.

**Comment by dancvrcek** [comment]
That would be grand!

**Comment by dancvrcek** [comment]
Hi Martin

Just tried to figure out how we could do that. I think the simplest version would:
1. move main() code into a new method execute() of the GPTool class.
2. replacing System.out calls with adding strings to a StringBuilder - so it can be redirected or printed out with a simple System.out.print()

... but not sure what your plan is.

**Comment by martinpaljak** [comment]
I don't see this as actionable currently, so after I push the refactor of 0.4, please have a fresh look
