### ISSUE TITLE
Do not fail silently

### ISSUE THREAD

**Issue by user8547** [martinpaljak/GlobalPlatformPro#50]
Currently if card or reader is not plugged in the tool will silently quit without giving any error message.
Would be nice to have something being output on the screen.

**Comment by martinpaljak** [comment]
It is not "failing", it is "doing nothing" :) But agreed, it has confused myself every now and then.

**Comment by user8547** [comment]
There should be some consistency.

When installing applet: "CAP loaded" is printed.
When deleting applet nothing is printed. E.g., "CAP removed" would be nice.

**Comment by martinpaljak** [comment]
Yes and no. Installation consists of two steps: LOAD + INSTALL, whereas deletion is a single step command. I'd like to keep it "unix style" which means no output unless there's an error. At the same time, getting some verebose information with -v would be nice. But there's a lot of stuff that gets thrown at the user with -v, maybe that needs some further work.

**Comment by user8547** [comment]
Number of steps involved should not matter. Either you inform the user about the activities being done or not.

Currently when deleting the applet I have no idea whether applet was deleted or the card/reader was not detected. These two cases should be distinguished somehow. Either by adding output in case of success or error.
