### ISSUE TITLE
Exception when installing CAP without applet AID

### ISSUE THREAD

**Issue by ThomasStoneJC** [martinpaljak/GlobalPlatformPro#51]
Hi,
I get an exception when installing a CAP file, that has a package without applet and therefore no applet AID.

```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
at java.util.ArrayList.rangeCheck(ArrayList.java:653)
at java.util.ArrayList.get(ArrayList.java:429)
at pro.javacard.gp.GPTool.main(GPTool.java:567)

```
Commit is 276edf5313efce4fa7da30b3381060f90508de4a

Cheers,
Thomas

**Comment by martinpaljak** [comment]
Thanks, will fix ASAP (weekend)

**Comment by martinpaljak** [comment]
Just for the record: you are supposed to use -load, not -install for such cap-s. But an exception is not allowed behaviour nevertheless.

**Comment by ThomasStoneJC** [comment]
Thank you!
Didn't know about the load command, just looked at the usage examples. My bad ; )
