### ISSUE TITLE
the problem with the default setting of the applet

### ISSUE THREAD

**Issue by BushKape** [martinpaljak/GlobalPlatformPro#52]
by entering the --make-default d1d2d3d4d501, gives an error install for make selectable failed sw: 6a86

**Comment by BushKape** [comment]
thanks for the help in advance

**Comment by martinpaljak** [comment]
This only works with a few cards under certain conditions. I'll document that more clearly

**Comment by BushKape** [comment]
I'm writing a thesis on java card, and met with the problem of proper installation. task work: do a full installation of the code of the electronic purse. I have a card nxp 2ja 2.4.1. For assistance would be very grateful!

**Comment by martinpaljak** [comment]
proper installation is done via INSTALL method. I'll mark the method as "unsupported" or "experimental"

**Comment by BushKape** [comment]
one more question: what should be a set of command?
