### ISSUE TITLE
Smartcafe Expert 64 V2

### ISSUE THREAD

**Issue by abdelhak-mes** [martinpaljak/GlobalPlatformPro#54]
Hi, 
I have some smartcafe expert card, i can't use all of them. 
Each time i try the **gp -l** 
A response : 
**Exception in thread "main" java.lang.IllegalStateException: No selected ISD!**

I tried to use the **gp -emv** as said in the https://github.com/martinpaljak/GlobalPlatformPro/tree/master/docs/TestedCards, **Virgin cars require unlocking with "-emv"**. but no way it still gives the same exception. 

Any idea ?
Thx.

**Comment by martinpaljak** [comment]
Please follow the support guideline, which means giving the full log. I suspect these are such old cards that the autodiscovery does not work.

**Comment by martinpaljak** [comment]
No reply - no issue. There is a way to "hide" ISD by changing the AID to a not-well-known AID and have your own application as default selected, in which case the discovery method will not know who to talk to. In such cases, usage of `-sdaid` shall be mandatory.
