### ISSUE TITLE
Latest version doesn't allow non-default key set version

### ISSUE THREAD

**Issue by minkyn** [martinpaljak/GlobalPlatformPro#55]
It seems that it used to be supported, but got commented as a FIXME in the latest version:

https://github.com/martinpaljak/GlobalPlatformPro/blob/master/src/pro/javacard/gp/GPTool.java#L306

Any reason why you cannot just uncomment it? In my case, I need to specify a different key version other than 0.

**Comment by minkyn** [comment]
https://github.com/martinpaljak/GlobalPlatformPro/pull/57

**Comment by minkyn** [comment]
Please please respond and review my PR.

**Comment by martinpaljak** [comment]
It is part of a bigger overhaul to fluently support multiple security domains and keysets. Both "source" and "target" keysets must be specified, from the command line, and that requires more explicit knowledge of where and why the keys/versions given on the command line shall be used. This is still work in progress, so will change in the near future.
