### ISSUE TITLE
Card cryptogram invalid

### ISSUE THREAD

**Issue by kg413** [martinpaljak/GlobalPlatformPro#58]
Ran into this error with Gemalto Cyberflex Access 64K v2c (TOP IM FIPS CY2) cards.  What might be causing it?

Log:

C:\Users\user\Downloads\gp>gp -sdaid A000000003000000 -l -d -v
[DEBUG] PlaintextKeys - static keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
# Detected readers from JNA2PCSC
[*] Broadcom Corp Contacted SmartCard 0
SCardConnect("Broadcom Corp Contacted SmartCard 0", T=*) -> T=0, 3B959540FFAE01030000
SCardBeginTransaction("Broadcom Corp Contacted SmartCard 0")
Reader: Broadcom Corp Contacted SmartCard 0
ATR: 3B959540FFAE01030000
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3B959540FFAE01030000

A>> T=0 (4+0008) 00A40400 08 A000000003000000 00
A<< (0027+2) (38ms) 6F198408A000000003000000A50D9F6E062091010342759F6501FF 9000
[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000003000000
[WARN] GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E06209101034275
[DEBUG] GlobalPlatform - Auto-detected block size: 255
A>> T=0 (4+0008) 80500000 08 EC7ADDC16616B17C 00
A<< (0028+2) (78ms) 0000600026101842A56B0101C3D8E4783663B864DC2C7B8F366375B4 9000
[DEBUG] GlobalPlatform - Host challenge: EC7ADDC16616B17C
[DEBUG] GlobalPlatform - Card challenge: C3D8E4783663B864
[DEBUG] GlobalPlatform - Card reports SCP01 with version 1 keys
[DEBUG] PlaintextKeys - session keys:
ENC: Ver:0 ID:0 Type:DES3 Len:16 Value:DABBF6794A04F4316D5BF0579F1EF37D KCV: A77644
MAC: Ver:0 ID:0 Type:DES3 Len:16 Value:DABBF6794A04F4316D5BF0579F1EF37D KCV: A77644
KEK: Ver:0 ID:0 Type:DES3 Len:16 Value:404142434445464748494A4B4C4D4E4F KCV: 8BAF47
pro.javacard.gp.GPException: STRICT WARNING: Card cryptogram invalid!
Card: DC2C7B8F366375B4
Host: 9555CB3EFB52130A
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
        at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:207)
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:583)
        at pro.javacard.gp.GPTool.main(GPTool.java:463)

**Comment by minkyn** [comment]
Either your key is invalid, or the key used is not SCP01

**Comment by martinpaljak** [comment]
IIRC all Gemalto cards used key diversification and/or the special master key. I don't have at hand these cards right now to test, but you can try:

gp -visa2 -key 47454D5850524553534F53414D504C45

Unless you prove that some calculations are incorrectly done, this is not a bug. You *need* to know the correct keying information to your cards, noone else can help you with that.
