### ISSUE TITLE
-scp option not working properly with gp.exe

### ISSUE THREAD

**Issue by bleu0909** [martinpaljak/GlobalPlatformPro#59]
I have two commands that expected to behave the same:
`gp -key-enc 404142434445464748494a4b4c4d4e4f -key-kek 404142434445464748494a4b4c4d4e4f -key-mac 404142434445464748494a4b4c4d4e4f -mode mac keyid 0 keyver 0 -sdaid A000000151000000 -debug -list`

`gp -key-enc 404142434445464748494a4b4c4d4e4f -key-kek 404142434445464748494a4b4c4d4e4f -key-mac 404142434445464748494a4b4c4d4e4f -mode mac -scp 2 keyid 0 keyver 0 -sdaid A000000151000000 -debug -list`

The only difference is the addition of "-scp 2" in the second command. The card clearly supports scp 02. The options are explicitly stated.

The first command is okay in external authentication. The second command is not okay in external authentication (0x6982).

I need to understand what could be the issue I am encountering right now. I tried some proprietary tools and it works perfectly but I need to make it work here in GlobalPlatformPro.
Thanks

**Comment by martinpaljak** [comment]
Obviously this is a bug or regression, if so.

Please provide the logs as specified in the support section of the README.

**Comment by bleu0909** [comment]
Hi, 
These are the traces,
Thanks
[withoutscp.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/680254/withoutscp.txt)
[withscp.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/680255/withscp.txt)

**Comment by bleu0909** [comment]
Hi,
These are the traces
[withoutscp.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/680256/withoutscp.txt)
[withscp.txt](https://github.com/martinpaljak/GlobalPlatformPro/files/680257/withscp.txt)

Thanks,

**Comment by martinpaljak** [comment]
This bug has been fixed in upcoming 0.4 release, but the location of it is hairy, so further refactorings will hopefully not mess up the fix.

Why do you need to specify the SCP version explicitly?
