### ISSUE TITLE
GPTool - allow stdout/stderr redirection to PrintStreams

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#60]
I remember you saying that you don't want to turn the project into one-size-fits-all-needs but I want to try my luck.

The request is to enable re-direction of logs into files or strings. The change would require:
1. adding two new class variables
	protected PrintStream out = System.out;
	protected PrintStream err = System.err;

2. adding a new method
	public static OptionSet parseArguments(String[] argv, PrintStream out, PrintStream err) 
which would set out/err to provided values, or keep them as System.out, System.err

3.  changing all outputs from standard ones to out/err.

**Comment by martinpaljak** [comment]
For now, I do not intend to do these tricks. Instead, I have taken an approach of splitting the functionality between three classes:
- GPTool - CLI handling (mostly dealing with options in a DWIM way). Intended to be used from command line, with stdin/stdout handled as any other UNIX command
- GPCommands - higher level operations currently in GPTool huge monolithic if/then chain, in a re-usable state, with some meaningful error checks. If there are methods that generate output (like dumping registry) you can give the output streams as arguments.
- GlobalPlatform - secure session handling and translation of GP* object namespace to APDU-s. With proper logging with slf4j and no output whatsoever, only exceptions.

I think this approach will satisfy your needs as well (but will require quite a bit of refactoring)
