### ISSUE TITLE
GPTool - make "gp" and "card" vars persistent between calls of the "work" method

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#61]
We find this quite useful for our experiments when we need to avoid deselects and resets when we call "work" method repeatedly.

The change possibly requires moving declarations into the class and doing the initial select of the card manager only when we do connect & getChannel. .... I think

**Comment by martinpaljak** [comment]
The whole GPPro huge main should be split, which is a work in process

**Comment by martinpaljak** [comment]
The whole CLI/operation handling is refactored in upcoming 0.4 version, so please open any new requests after you have tried the new version
