### ISSUE TITLE
No communication with Library / PCSCD service

### ISSUE THREAD

**Issue by surendra060** [martinpaljak/GlobalPlatformPro#65]
Hii Martin

1. **Environment** : Ubuntu 16.04 and  OpenJDK ver  jdk1.8.0_92.
I am using gp.jar file from Applet Playground and on running various gp.jar with various switches  i Get the following :-
surendra@LXBOX-SS:~/Desktop/AppletPlayground-master$ java -jar gp.jar -l
surendra@LXBOX-SS:~/Desktop/AppletPlayground-master$ java -jar gp.jar -d -i
# Detected readers from None
surendra@LXBOX-SS:~/Desktop/AppletPlayground-master$ java -jar gp.jar --debug --info
# Detected readers from None
surendra@LXBOX-SS:~/Desktop/AppletPlayground-master$ java -jar gp.jar -atr

2.  **However the Card reader and associated libccid and pcscd tools are working fine as per the status below.**

surendra@LXBOX-SS:~/Desktop/AppletPlayground-master$ pcsc_scan 
PC/SC device scanner
V 1.4.25 (c) 2001-2011, Ludovic Rousseau <ludovic.rousseau@free.fr>
Compiled with PC/SC lite version: 1.8.14
Using reader plug'n play mechanism
Scanning present readers...
0: Gemalto PC Twin Reader 00 00

Fri Mar 17 10:15:36 2017
Reader 0: Gemalto PC Twin Reader 00 00
  Card state: Card inserted, 
  ATR: 3B 2A 00 80 65 A2 01 01 01 3D 72 D6 43

ATR: 3B 2A 00 80 65 A2 01 01 01 3D 72 D6 43
+ TS = 3B --> Direct Convention
+ T0 = 2A, Y(1): 0010, K: 10 (historical bytes)
  TB(1) = 00 --> VPP is not electrically connected
+ Historical bytes: 80 65 A2 01 01 01 3D 72 D6 43
  Category indicator byte: 80 (compact TLV data object)
    Tag: 6, len: 5 (pre-issuing data)
 
Possibly identified card (using /home/surendra/.cache/smartcard_list.txt):
3B 2A 00 80 65 A2 01 01 01 3D 72 D6 43
3B 2A 00 80 65 A2 01 .. .. .. 72 D6 43
	Gemplus MPCOS EMV 4 Byte sectors
3B 2A 00 80 65 A2 01 01 01 3D 72 D6 43
	GEMPLUS Logico Secure SmartCard for Citrix Metaframe
	PTTPost Easy Stamp
	Hungarian student card

3. I have also reinstalled Java packages still there is a problem. The reader/card is not detected even though i have created a seperate directory in /usr/lib for linking of libpcsclite as per the following command , (by referreing to one of old issue)

sudo ln -s /lib/x86_64-linux-gnu/libpcsclite.so.1.0.0  /usr/lib64/libpcsclit.so

4. The issue still persists and it seems that go.jar is not able to communicate to underlying drivers. Any pointers to resolve issue will be highly appriciated.

Cheers

**Comment by martinpaljak** [comment]
I just tried with 16.04 on amd64 and had no problems. gp.jar takes care of the possible need for referencing the pcsclite library, no need to mess around with the library symlinks.
(If you think that is the problem, re-run Java with "java -Dsun.security.smartcardio.library=/path/to/libpcsclite.so -jar gp.jar -ldv"

**Comment by martinpaljak** [comment]
Also, please follow the technical support guielines: https://github.com/martinpaljak/GlobalPlatformPro#contact

**Comment by surendra060** [comment]
OK never mind, I resolved after struglling for a couple of days by using latest release of gp.jar..
Thanx
