### ISSUE TITLE
Unable to install applet using gp.jar utility

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#72]
I am using gp.jar to install my applet on Morpho Smart Card using command below:

Overriding my default keys:

java -jar gp.jar -key XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
java -jar gp.jar -key-mac XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
java -jar gp.jar -key-enc XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
java -jar gp.jar -key-kek XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

installing Applet:

java -jar gp.jar -install myApplet.cap

However I continuously getting below exception at console.

pro.javacard.gp.GPException: STRICT WARNING: Card cryptogram invalid!
Card: XXXXXXXXXXXXXXX
Host: XXXXXXXXXXXXXXX
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
        at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:207)
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:583)
        at pro.javacard.gp.GPTool.main(GPTool.java:463)

Any help in this regard would be highly appreciated.

Note: I have build my applet with ant-javacard, Java card Version 3.0.2.

**Comment by martinpaljak** [comment]
You need to give the key with every command (and either a master key or 3 different keys)

**Comment by naeemgik** [comment]
I am specifying key as i mention in my question, however despite the keys it give me exception of Card cryptogram invalid

**Comment by naeemgik** [comment]
I am using below command:
java -jar gp.jar  -key <master_key_here> -install myApplet.cap

While still getting same exception:

pro.javacard.gp.GPException: STRICT WARNING: Card cryptogram invalid!
Card: 8CAD8A953D5611BB
Host: 5365617F4C4B8692
!!! DO NOT RE-TRY THE SAME COMMAND/KEYS OR YOU MAY BRICK YOUR CARD !!!
        at pro.javacard.gp.GlobalPlatform.giveStrictWarning(GlobalPlatform.java:207)
        at pro.javacard.gp.GlobalPlatform.openSecureChannel(GlobalPlatform.java:583)
        at pro.javacard.gp.GPTool.main(GPTool.java:463)

**Comment by martinpaljak** [comment]
I would guess that the card uses key diversification. If you know which algorithm, you can try the ones implemented: -emv or -visa2.

If the diversification algorithm is not known, you need to implement it or provide information about the diversification method so that I could include it in the release.

**Comment by naeemgik** [comment]
Martin,
Thanks for you valuable cooperation.

The issue was with diversified Key, The following command worked for us.

java -jar gp.jar -key <master_ke> -emv <diversifiedKey> -install myApplet.cap

Thanks again :)
