### ISSUE TITLE
General JC question - applet with custom library packages

### ISSUE THREAD

**Issue by dancvrcek** [martinpaljak/GlobalPlatformPro#73]
I wonder if you can help. We build an opensource crypto library for javacards. We'd like to structure it into packages similarly to BouncyCastle crypto but not sure if it's possible at all with javacard kit tools.

We can create EXP files and compile the applet using EXP files of our crypto packages. However, Converter doesn't include library classes into the CAP file.

Is there a solution for a) load libraries into JavaCards, or b) include all libraries into the applet CAP file?

PS: the code itself comes together nicely and will [present it](https://www.blackhat.com/us-17/briefings/schedule/#opencrypto-unchaining-the-javacard-ecosystem-7606) at Black Hat tomorrow, but it would be great to give it a reasonable structure.

**Comment by martinpaljak** [comment]
You should be able to load non-applet CAP-s with -load

**Comment by dancvrcek** [comment]
cool - one problem solved.

Another one though is - can I create a cap without an instance of the Applet class?

**Comment by dancvrcek** [comment]
ha - I can do it by calling converter with -out JCA and then using capgen.

I will let you know if I manage to successfully install the whole thing

**Comment by martinpaljak** [comment]
I think the question belongs to ant-javacard if anywhere ?

**Comment by dancvrcek** [comment]
possibly - one problem with 2 tools to work together. I managed to create cap files, load library ones to smartcard. Some code problems to resolve, but it looks good.
