### ISSUE TITLE
How to test compliance level of  GlobalPlatform version

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#75]
Using gp.jar I am able to install the applet on my java card which was compatible with GlobalPlatform secification 2.1.1

Now I  have a new Java smart card and the vendor claims that it support Global Platform version 2.2.1. How I can test and verify that whether it exactly support this global platform version. Can you please help me in this regard?

**Comment by martinpaljak** [comment]
What are the features from 2.2.1 that you require? gp -dvi will give you information about GP versions detected or used (if reported from card)

**Comment by naeemgik** [comment]
Martin,

Thanks for your reply.

I  have different vendors smart cards. When i run the command java -jar gp.jar -dvi some of the cards does not give me GlobalPlatform version like for one vendor it gives:

[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000151000000
[DEBUG] GlobalPlatform - Auto-detected GP version: GP22
[WARN] GlobalPlatform - Unknown/unhandled tag in FCI proprietary data: 9F6E06129
161530400

while for others:

[DEBUG] GlobalPlatform - Auto-detected ISD AID: A000000151000000
[DEBUG] GlobalPlatform - Auto-detected block size: 255

Not showing GlobalPlatform version. what does that means?

**Comment by martinpaljak** [comment]
This means that the card(Chinese?) does not contain those data tags (could be considered violation of spec)

The purpose of gppro is to provide an easy to use tool, even for quirky and proprietary cards, if possible within the very broad interpretation of the public specifications. Evaluation of conformance is not in scope.
