### ISSUE TITLE
Command failed - Logical channel no supported or is not active SW = 6881

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#77]
Martin,

This is my 3rd question so thousands apologies :) always found you extremely helpful.

Using GlobalPlatformPro I am able to install applet and select the applet. However when i send any command using "channel.transmit(command);" it gives exception 

Command failed - Logical channel no supported or is not active with status word 6881.

Can you please help me in pointing out the issue. what i am doing wrong?

Thanks
Naeem

**Comment by dancvrcek** [comment]
do you open the channel first?

context = TerminalFactory.getDefault();
CardTerminals terminals = context.terminals();
... choose a terminal -> m_terminal
m_card = m_terminal.connect("*");
m_channel = m_card.getBasicChannel();
...

that should work

**Comment by martinpaljak** [comment]
How do you use GPPro in this context? It assumes "plain" apdu BIBO (bytes in, bytes out) and encodes the basic channel.

**Comment by naeemgik** [comment]
I am using below code snippet from GP Pro:

final TerminalFactory context = TerminalFactory.getDefault();
		CardTerminals terminals = context.terminals();
		List<CardTerminal> do_readers = terminals.list(State.CARD_PRESENT);
		CardTerminal reader = do_readers.get(0);

		try {
			// Establish connection
			try {
				card = reader.connect("*");
				// Use use apdu4j which by default uses jnasmartcardio which
				// uses real SCardBeginTransaction
				card.beginExclusive();
			} catch (CardException e) {
				System.err.println("Could not connect to " + reader.getName() + ": " + TerminalManager.getExceptionMessage(e));
			}

			// GlobalPlatform specific
		    channel = card.getBasicChannel();
			gp = new GlobalPlatform(channel);
		} catch (Exception e) {
			e.printStackTrace();
		}

CommandAPDU command = new CommandAPDU(CLASS, INST, (byte) 0, (byte) 0, 256);
		ResponseAPDU resp = channel.transmit(command);
		if (resp.getSW() == 0x9000) {
			System.out.println("CIN " + HexUtils.bin2hex(resp.getData()));
		} else {
			throw new Exception("Invalid Status Word : " + resp.getSW());
		}

**Comment by naeemgik** [comment]
When I use the the below command in argumenets using the orginal GP pro source code:
-dv -key 404142434445464748494A4B4C4D4E4F -apdu EE00000008313337303032353000
It gives me error:

PC/SC failure: SCARD_W_RESET_CARD

**Comment by martinpaljak** [comment]
Okay. So this seems to be a question about general smart card coding (you are sending random APDU-s to the card).

The relation of GP to channels is explained in GP 2.2.1 sections 6.3 and 6.4
You should read about logical channels in ISO 7816 as well, and for your own application, carefully read the MultiSelectable in JC (https://docs.oracle.com/javacard/3.0.5/api/javacard/framework/MultiSelectable.html) and javax.smartcardio.

The only missing feature from GPPro in that sense is "meaningful support" for "Implicit Selection Parameter", but which will be added when the need arises.
