### ISSUE TITLE
Question: GP Pro support Derivation algorithm: CMK (CGP 2.04) ?

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#78]
Does the GP Pro support Derivation algorithm: CMK (CGP 2.04) ? 
If yes How?

**Comment by martinpaljak** [comment]
Please elaborate.

**Comment by martinpaljak** [comment]
Because first googling seems to suggest an answer along the lines of "yes, homo sapiens is supported as a user" 

![screenshot at 2017-08-18 16-45-46](https://user-images.githubusercontent.com/46006/29461551-d374db44-8434-11e7-895f-24a7a0d0a83f.png)

**Comment by naeemgik** [comment]
I mean can i install the applet on card having Derivation algorithm: CMK (CGP 2.04) using gp.jar? Currenly I am unable to install the applet on such cards. How to to install applet having this derivation algorithm?

**Comment by martinpaljak** [comment]
What is "CMK CGP 2.04" ? A link to some kind of documentation? You can use whatever kind of diversification for the keys, if the methods in the utility are not enough, you can create your own SessionKeysProvider that diverisifes keys the way you need.

**Comment by martinpaljak** [comment]
Not actionable, sorry.
