### ISSUE TITLE
Access Control Rules

### ISSUE THREAD

**Issue by bertrandmartel** [martinpaljak/GlobalPlatformPro#81]
I recently needed to use Access Control rules to have the Access Control Enforcer (on Android via [openmobileapi](https://github.com/seek-for-android/pool)) to authorize APDU sent from my application. Those rules match AID/certificate hash (20 byte SHA1) and more APDU filters.
This API is well documented in Global Platform specification as "Secure Element Access Control".
Presently, with GlobalPlatformPro, we can access it using

* get rules
```bash
gp -a 00A4040009A00000015141434C00 -a 80CAFF4000
```
* store rules (via install for personalization)
```bash
gp -key-enc $KEY_ENC -key-kek $KEY_KEK -key-mac $KEY_MAC  -app A00000015141434C00 --store-data F031E22FE1284F10D2760001180002FF49502589C0019B01C11454AC1FC8DB794570D0CF2565DBFBE98C266AE07FE303D00101
```
* delete rules (via install for personalization)
```bash
gp -key-enc $KEY_ENC -key-kek $KEY_KEK -key-mac $KEY_MAC  -app A00000015141434C00 --store-data F1124F10D2760001180002FF49502589C0019B01
```
This works great but it's not very readable and it requires to build request manually so I decided to implement the access control specification in your tool to be able to have something more fancy 

This is what I've implemented so far : 

* list all rules
```bash
gp -acr-list

RULE #0 :
       AID  : D2760001180002FF49502589C0019B15
       HASH : 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F
       APDU rule   : ALWAYS(0x01)
       APDU filter : 
RULE #1 :
       AID  : D2760001180002FF49502589C0019B18
       HASH : 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F
       APDU rule   : ALWAYS(0x01)
       APDU filter : 
```
* add a rule with specified aid, hash and rule type (install for personalization)
```
gp -acr-add -hash 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F -app D2760001180002FF49502589C0019B18 -rule 01
```
`rule` to 0x01 means `ALWAYS`, 0x00 means `NEVER`. Anything other than those 2 values can be an apdu filter as specified in Secure Element Access control 1.0 p48). Example 

```
gp -acr-add -hash 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F -app D2760001180002FF49502589C0019B18 -rule 0102030401020304
```
which would give the following with `-acr-list` 

```
RULE #0 :
       AID  : D2760001180002FF49502589C0019B15
       HASH : 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F
       APDU rule   : ALWAYS(0x01)
       APDU filter : 
RULE #1 :
       AID  : D2760001180002FF49502589C0019B18
       HASH : 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F
       APDU rule   : CUSTOM(0x02)
       APDU filter : 0102030401020304
```

* delete a rule by AID (install for personalization)
```
gp  -acr-delete -app D2760001180002FF49502589C0019B17
```
* delete a rule by AID and hash (install for personalization)
```
gp  -acr-delete -app D2760001180002FF49502589C0019B17 -hash 53AC1FC8DB794570D0CF2565DBFBE98C266AE07F
```
What do you think about it ?

**Comment by martinpaljak** [comment]
I think it might be useful to others as well, thanks!

**Comment by bertrandmartel** [comment]
@martinpaljak I've build this [ARA-M applet](https://github.com/bertrandmartel/aram-applet) implementation. It works with store data from the ISD (via install for personalization) or with raw APDU. So this can be used as testing applet for the Access Control feature in GlobalPlatformPro.

The install for personalization works fine if I install the applet on a SIM card (with a different AID not to interfere with the builtin ARA-M). But I didn't succeed in sending the install for personalization with SmartCafe smartcard : bertrandmartel/aram-applet#1. Do you know what may be the issue here ?
