### ISSUE TITLE
Problem with GET STATUS

### ISSUE THREAD

**Issue by fraschu-gd** [martinpaljak/GlobalPlatformPro#83]
Hello Martin!

We have a problem using GPTool with a G+D SCE 7.0 card. When installing an application it shows the following behavior:

`$ gp -key-mac 404142434445464748494A4B4C4D4E4F -key-enc 404142434445464748494A4B4C4D4E4F -key-kek 404142434445464748494A4B4C4D4E4F -in
stall CALC.cap
ATTENTION: Overriding default keys ...
Exception in thread "main" java.lang.IllegalArgumentException: AID's are between 5 and 16 bytes, not 1
        at pro.javacard.gp.AID.<init>(AID.java:67)
        at pro.javacard.gp.AID.<init>(AID.java:43)
        at pro.javacard.gp.GPRegistry.populate_tags(GPRegistry.java:234)
        at pro.javacard.gp.GPRegistry.parse(GPRegistry.java:288)
        at pro.javacard.gp.GlobalPlatform.getStatus(GlobalPlatform.java:1051)
        at pro.javacard.gp.GlobalPlatform.getRegistry(GlobalPlatform.java:983)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:631)
        at pro.javacard.gp.GlobalPlatform.loadCapFile(GlobalPlatform.java:625)
        at pro.javacard.gp.GPTool.main(GPTool.java:568)`

We tracked the issue down to a problematic implementation in populate tags() (in GPRegistry). It uses the BouncyCastles ASN.1 parser and more specific getApplicationTag() to retrieve the tags. Now BouncyCastle masks out the tags internally with a 0x1f. So from a 0x4f tag in the response remains 0x0f. That's what it is checking for when retrieving an AID of an application or load file.

` --> 84 F2 80 02 0A
     4F 00 A6 18 34 C2 DB 0D 63 85 `
` <-- E3 46 4F 08 A0 00 00 00 03 00 00 00 9F 70 01 01 
     C5 03 9E FE 80 CF 01 40 CF 01 41 CF 01 42 CF 01 
     43 CF 01 80 CF 01 81 CF 01 82 CF 01 83 C4 0B D2 
     76 00 00 05 AA FF CA FE 00 01 CE 02 00 01 CC 08 
     A0 00 00 00 03 00 00 00 
`

Now the problem is that the SCE 7.0 GET STATUS response (see above) contains more tags - in this case optional CF tags (Implicit Selection Parameters). This is valid according to the GP Specification v2.2.1 When applying the mask 0x1f to 0xcf also 0x0f remains and the parser runs into the AID case and fails.

We temporarily fixed the issue by checking the length of the TLV. A final solution should probably take a different approach. If there is no way to get the original tag from Bouncy Castle you eventually have to replace the TLV parser by something else.

Hope to hear from you soon!

Best regards,
Frank

**Comment by tomo-ms** [comment]
Hi Frank

I have a same problem, so I have replaced the TLV parser to evsinev/ber-tlv.
https://github.com/tomo-ms/GlobalPlatformPro/tree/get_status_tlv_fix2

Currently, this code is not tested well and I'll do it in next week.
After finishing test in my environment, I'd like to pull request.

Thanks,
Tomo-ms

**Comment by martinpaljak** [comment]
Hello,

The data structure parsing is a mess, to be honest, and fixes-improvements-replacements are most needed. If possible, I'd like to continue with BC, but some sensible and easy to use parser could be used as well.

**Comment by martinpaljak** [comment]
This specific issue should be fixed in latest master and published really soon. Thanks for the hint on ber-tlv lib, it works pretty well.
