### ISSUE TITLE
[Request] Parse the APDU response and print human readable error message

### ISSUE THREAD

**Issue by dogtopus** [martinpaljak/GlobalPlatformPro#84]
While working with the card, I found myself constantly checking the response table (like https://eftlab.co.uk/index.php/site-map/knowledge-base/118-apdu-response-list) when errors pop up. It would be nice to print human readable error message along with the raw APDU response code (like "Some command failed: Conditions of use not satisfied (6985)")

**Comment by martinpaljak** [comment]
Indeed. Can you provide a patch?

**Comment by martinpaljak** [comment]
I added some SW-s from GlobalPlatform specification, that get automatically added in exception messages, that will then result in text being shown to the user about the SW.

Eventually SW-s should be masked and human readable conditions given, IF there is a chance that user action will change the result. That might not always be the case (eg "wrong length" most probably means bug in GPPro)
