### ISSUE TITLE
findbugs : ignore EI_EXPOSE_REP2 & EI_EXPOSE_REP

### ISSUE THREAD

**Issue by bertrandmartel** [martinpaljak/GlobalPlatformPro#86]
IMHO, ignoring `EI_EXPOSE_REP` & `EI_EXPOSE_REP2` should be fine. What do you think ? 
Possibility to add exclude filter file like : https://stackoverflow.com/a/23551339/2614364. I've tried that but it's excluding all rules, I'm not accustomed to findbugs (have used [PMD](https://pmd.github.io/) in the past)

Description of EI_EXPOSE_*

> EI: May expose internal representation by returning reference to mutable object (EI_EXPOSE_REP)
> 
> Returning a reference to a mutable object value stored in one of the object's fields exposes the internal representation of the object.  If instances are accessed by untrusted code, and unchecked changes to the mutable object would compromise security or other important properties, you will need to do something different. Returning a new copy of the object is better approach in many situations.
> 
> EI2: May expose internal representation by incorporating reference to mutable object (EI_EXPOSE_REP2)
> 
> This code stores a reference to an externally mutable object into the internal representation of the object.  If instances are accessed by untrusted code, and unchecked changes to the mutable object would compromise security or other important properties, you will need to do something different. Storing a copy of the object is better approach in many situations.
> 
>

**Comment by martinpaljak** [comment]
I gave it some thought and while I like the brevity of using static fields with byte arrays directly, I also understand the reasoning behind the find. So either playing with visibility of fields or adding getters for things that are expected to be used by outside code (eg, not gp tool) might make sense.
