### ISSUE TITLE
Add SD related interface (domain installation)

### ISSUE THREAD

**Issue by martinpaljak** [martinpaljak/GlobalPlatformPro#9]
- [x] interface for domain creation from command line
- [x] expose all privileges to command line
- [x] key loading to security domains, in addition to `-lock/-unlock`
  - [x] asymmetric key loading from a file
- [x] Extending GPKey to support RSA and ECC

**Comment by jmrgibson** [comment]
Hey @martinpaljak, I'm using your project to create SDs with mandated DAP using ECC keys. At the moment its pretty hacky, but if you'd like I can tidy it up some and make a PR to finish this out.

**Comment by martinpaljak** [comment]
Sure, fire it up

**Comment by martinpaljak** [comment]
@jmrgibson version 0.4 is coming out in a few days, which has greatly improved internals with a LOT of refactoring. Probably your PR would not apply, but I would still appreciate if you filed it against the version you made. No DAP support, yet.

**Comment by martinpaljak** [comment]
This is obsolete now.
