### ISSUE TITLE
Ant build fails - ProGuard reports "No such file or directory"

### ISSUE THREAD

**Issue by TobiasKaiser** [martinpaljak/GlobalPlatformPro#93]
The result of running `ant -verbose` on a freshly cloned GlobalPlatformPro repository fails with the following error:

> Apache Ant(TM) version 1.9.9 compiled on March 1 2017
> Trying the default build file: build.xml
> Buildfile: /home/tobias/workspace/javacard/GlobalPlatformPro/build.xml
> Detected Java version: 1.8 in: /usr/lib/jvm/java-8-openjdk-amd64/jre
> Detected OS: Linux
> parsing buildfile /home/tobias/workspace/javacard/GlobalPlatformPro/build.xml with URI = file:/home/tobias/workspace/javacard/GlobalPlatformPro/build.xml
> Project base dir set to: /home/tobias/workspace/javacard/GlobalPlatformPro
> parsing buildfile jar:file:/usr/share/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml with URI = jar:file:/usr/share/ant/lib/ant.jar!/org/apache/tools/ant/antlib.xml from a zip file
> Build sequence for target(s) `dist' is [fetch, dist]
> Complete build sequence is [fetch, dist, clean, javadoc, release, windist, ]
> 
> fetch:
>     [mkdir] Created dir: /home/tobias/workspace/javacard/GlobalPlatformPro/lib
>       [get] Getting: http://central.maven.org/maven2/net/sf/proguard/proguard-base/5.3/proguard-base-5.3.jar
>       [get] To: /home/tobias/workspace/javacard/GlobalPlatformPro/lib/proguard-base-5.3.jar
>       [get] ....................................................
>       [get] ....................................................
>       [get] .....................
> 
> dist:
>      [java] Executing '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java' with arguments:
>      [java] '-classpath'
>      [java] '/home/tobias/workspace/javacard/GlobalPlatformPro/lib/proguard-base-5.3.jar'
>      [java] 'proguard.ProGuard'
>      [java] '@globalplatform.pro'
>      [java] 
>      [java] The ' characters around the executable and arguments are
>      [java] not part of the command.
>      [java] ProGuard, version 5.3
>      [java] Reading program jar [/home/tobias/workspace/javacard/GlobalPlatformPro/target/gp.jar]
>      [java] Error: Can't read [/home/tobias/workspace/javacard/GlobalPlatformPro/target/gp.jar] (No such file or directory)
> 
> BUILD FAILED
> /home/tobias/workspace/javacard/GlobalPlatformPro/build.xml:19: Java returned: 1
> 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:115)
> 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
> 	at org.apache.tools.ant.Task.perform(Task.java:348)
> 	at org.apache.tools.ant.Target.execute(Target.java:435)
> 	at org.apache.tools.ant.Target.performTasks(Target.java:456)
> 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
> 	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
> 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
> 	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
> 	at org.apache.tools.ant.Main.runBuild(Main.java:857)
> 	at org.apache.tools.ant.Main.startAnt(Main.java:236)
> 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:287)
> 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:113)
> 
> Total time: 0 seconds

My operating system is Debian GNU/Linux 9.2 on arm64. My Java version is as follows:

> openjdk version "1.8.0_151"
> OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-1~deb9u1-b12)
> OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)

I have libccid, git, ant and openjdk-8-jdk installed (openjdk-7-jdk is not available easily for my OS.) I guess that the problem is that Java 8 breaks something.

The precompiled gp.jar from GitHub works without a problem so far in my environment.

**Comment by TobiasKaiser** [comment]
I just checked out the tag **v0.3.9** and there ant builds everything successfully. The error only appears when I try building v0.3.10rc3 or the master branch.

**Comment by martinpaljak** [comment]
Sorry about that, there is currently a bit of confusion until the recent refactorings are finished and documentation updated as well.

I intend to shift most of the usage instructions to the Wiki and expand a bit from the currently quite laconic command examples to actual "tutorial". 

https://github.com/martinpaljak/GlobalPlatformPro/wiki/Building

Will fix the building section of the README as well, but please keep in mind that the command line samples in the README might be out of date. Consult --help and if something does not work/feels awkward, let me know.

**Comment by martinpaljak** [comment]
I would hope Java 1.8 not breaking anything, but me breaking with ant->maven shift most probably ;) If things still do not work, let me know.

**Comment by TobiasKaiser** [comment]
Awesome, when I follow the instructions with maven from the wiki, it all works. Thanks! :smiley:
