### ISSUE TITLE
Sending raw APDU hex string gives java exception

### ISSUE THREAD

**Issue by erickjordan** [martinpaljak/GlobalPlatformPro#97]
$ java -jar target/gp.jar -key 404142434445464748494A4B4C4D4E4F -d -v -i -a 00a404000aa00000006203010c0101
GlobalPlatformPro v0.3.10rc5-10-g81bc314
Running on Linux 4.10.0-42-generic amd64, Java 1.8.0_152 by Oracle Corporation
Unlimited crypto policy is NOT installed!
# Detected readers from JNA2PCSC
[*] SCM Microsystems Inc. SCR 331 [CCID Interface] (SC215511100158) 00 00
SCardConnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (SC215511100158) 00 00", T=*) -> T=1, 3BFA1800008131FE454A33413038315632343189
SCardBeginTransaction("SCM Microsystems Inc. SCR 331 [CCID Interface] (SC215511100158) 00 00")
Reader: SCM Microsystems Inc. SCR 331 [CCID Interface] (SC215511100158) 00 00
ATR: 3BFA1800008131FE454A33413038315632343189
More information about your card:
    http://smartcard-atr.appspot.com/parse?ATR=3BFA1800008131FE454A33413038315632343189

SCardEndTransaction()
SCardDisconnect("SCM Microsystems Inc. SCR 331 [CCID Interface] (SC215511100158) 00 00", true)
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to [B
	at pro.javacard.gp.GPTool.main(GPTool.java:346)

**Comment by martinpaljak** [comment]
Thanks, obvious regression.

**Comment by martinpaljak** [comment]
https://github.com/martinpaljak/GlobalPlatformPro/releases/tag/v0.3.10rc7 should have this fixed
