### ISSUE TITLE
SCP03 mode 10 with AES128 bits keys - Incorrect C-MAC on External Authenticate

### ISSUE THREAD

**Issue by jcvinatier** [martinpaljak/GlobalPlatformPro#98]
The C-MAC of the External Authenticate command is incorrect (confirmed after computation of AES-CMAC algo on a paper).

Hereafter the trace releated to authentication from gp.exe -v -l command

[DEBUG] GlobalPlatform - Auto-detected ISD: [AID: A000000151000000]
Warning: no keys given, using default test key 404142434445464748494A4B4C4D4E4F
[DEBUG] GlobalPlatform - Host challenge: C81ED3B6B3DEF556
[DEBUG] GlobalPlatform - Card challenge: 86C8BD65FA1044EE
[DEBUG] GlobalPlatform - Card reports SCP03 i=10 keys 0
[DEBUG] GlobalPlatform - SCP03 i=16
[DEBUG] GlobalPlatform - Will do SCP03 (3)
[DEBUG] PlaintextKeys - Card keys: {
ENC=version=0 id=0 type=RAW bytes=404142434445464748494A4B4C4D4E4F, 
MAC=version=0 id=0 type=RAW bytes=404142434445464748494A4B4C4D4E4F, 
DEK=version=0 id=0 type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[DEBUG] PlaintextKeys - session keys: {
ENC=version=0 id=0 type=AES bytes=3D991C5571391EB5BEF93DB2A4FD13D8, 
MAC=version=0 id=0 type=AES bytes=9BAB6C2C1EFEAC6E4F3B214ABABAC3B1, 
DEK=version=0 id=0 type=RAW bytes=404142434445464748494A4B4C4D4E4F}
[DEBUG] GlobalPlatform - Verified card cryptogram: CF4A8EE6E34A4321
[DEBUG] GlobalPlatform - Calculated host cryptogram: DC79BEA879C62D44
External authenticate failed: 0x6982 (Security status not satisfied)

Sequence counter value is: 000001 
External Authenticate command sent by GPPro is: 8482010010DC79BEA879C62D44E7BA572F421CF33A
Correct C-MAC value shall be: CF49171F9CA98D8B

Session keys, challenges and cryptogram are OK. Only the C-MAC computation fails.

I am using gp.exe v0.3.10rc5 for Windows.

**Comment by martinpaljak** [comment]
Can you point a direction where to look for the cause?

**Comment by jcvinatier** [comment]
My mistake, the IV was not taken into account in my computation. You can close the issue.
Nevertheless, in GlobalPlatform.java line 586, it is not necessary to generate the EXTERNAL_AUTHENTICATE command with CLA='84' as it is overwritten in SCP03Wrapper.wrap to '84'. In wrap method, it would be better to only set b3 of CLA byte related to proprietary Secure Channel.
Still in wrap method, maybe it is stated in the documentation, Logical Channels are not managed for C-MAC computation.

**Comment by martinpaljak** [comment]
Logical channels are not supported, they "may happen to work" but that would be by accident.

Patches for other glitches are most welcome.

**Comment by typelogic** [comment]
I have a slightly related question. For `SCP02`,  is `MAC` a mandatory during `EXTERNAL_AUTHENTICATE` ? I have a JCOP shell session that shows otherwise.  Thanks for any tip about this.

**Comment by ernest-ochuke** [comment]
> I have a slightly related question. For `SCP02`, is `MAC` a mandatory during `EXTERNAL_AUTHENTICATE` ? I have a JCOP shell session that shows otherwise. Thanks for any tip about this.

Yes MAC is required to be calculated.
