### ISSUE TITLE
Install CAP file using SCP03

### ISSUE THREAD

**Issue by naeemgik** [martinpaljak/GlobalPlatformPro#99]
Hi,

My java card supports both SCP02 and SCP03, however when i install the CAP file the default setting is SCP02 as shown in logs:

[DEBUG] GlobalPlatform - Card reports SCP02 with version 255 keys.

Question is: How to force for SCP03?

My Card Supports SCP03 with:
  •         i = 00
  •         External Auth P1 : 
                o   C-MAC
                o   C-DECRYPTION and C-MAC

Thanks
@naeemgik

**Comment by martinpaljak** [comment]
Refer to your card platform (pre-)personalisation manual. This is usually proprietary and not in the scope of GlobalPlatform(Pro).

**Comment by naeemgik** [comment]
Secure channel Protocol SCP is pre-step of applet installation. That is what is going in openSecureChannel(...) of GlobalPlatformPro. So how my question is irrelevant and not in scope of GlobalPlatformPro?
